### ISSUE TITLE
Block of heigth X not found

### ISSUE THREAD

**Issue by SadBatman** [moneroexamples/onion-monero-blockchain-explorer#100]
I'm getting this error:

```
Block of height 10 not found in the blockchain!Attempt to get block from height 10 failed -- block not in db
Cant get block: 10
```

I'm running the explorer with this comment:

`./xmrblocks --bc-path ~/Coding/node_03 
`

Where the node_03 directory is used by the daemon.

The explorer only shows block 0 and none of the other ones.  Is this a known issue that perhaps was fixed in the devel branch ?

**Comment by moneroexamples** [comment]
Could you try with path to the lmdb folder where the blockchain files are stored:

`./xmrblocks --bc-path ~/Coding/node_03/lmdb`

**Comment by moneroexamples** [comment]
From lack of update, I guess it works now? I close it then. Please feel free to reopen if needed.
