### ISSUE TITLE
BSD-3 license note

### ISSUE THREAD

**Issue by instanceme** [moneroexamples/onion-monero-blockchain-explorer#101]
Just wanted to be sure before forking @moneroexamples -  should just leaving the license file as it is and adding our copyright notice to the readme is okay or should your copyright notice be included besides ours in the readme file too?

Thanks in advance.

**Comment by moneroexamples** [comment]
Dont know what are official ways of doing this, but the way monero project does is fine with me. They add one sentence to their MIT license referencing original cryptonote project which they forked off: https://github.com/monero-project/monero/blob/master/LICENSE
