### ISSUE TITLE
Error on compilation

### ISSUE THREAD

**Issue by yagamidev** [moneroexamples/onion-monero-blockchain-explorer#102]
Hello,
while running the compilation I get this error : 
``` 
 Scanning dependencies of target myxrm
[  5%] Building CXX object src/CMakeFiles/myxrm.dir/MicroCore.cpp.o
In file included from ~/onion/onion-blocks/src/MicroCore.h:10:0,
                 from ~/onion/onoin-blocks/src/MicroCore.cpp:5:
~/onioin-blocks/src/monero_headers.h:19:37: fatal error: release/version/version.h: No such file or directory
compilation terminated.
```

**Comment by moneroexamples** [comment]
You should try development branch of the explorer;

 - https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/devel

master branch wont compile with current master branch of monero.

**Comment by propercoil** [comment]
Or maybe you didn't specify the correct monero dir using:

`cmake -DMONERO_DIR=dir_here ..`

**Comment by yagamidev** [comment]
@propercoil Yeah you were right that was the problem.
Thanks.
