### ISSUE TITLE
wacky timestamps in mempool on xmrchain.net

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#109]
i updated daemon first, and thats when I started seeing the timestamps.

then I updated the explorer code, hoping it would fix. it did not.

**Comment by moneroexamples** [comment]
Trying to see what can be causing it. What makes it difficult is that I dont see this issue on my node and my local explorer, nor it shows on https://moneroexplorer.com. Did you try removing `poolstate.bin` file and flushing pool in the deamon?

**Comment by Gingeropolous** [comment]
im gonna try a fresh clone and build

**Comment by Gingeropolous** [comment]
nope, that didn't work

**Comment by moneroexamples** [comment]
I checked your testnet explorer, and timestamps there are fine: https://i.imgur.com/nxTWAWE.png. So this seems to affects mainnet only.

**Comment by Gingeropolous** [comment]
finally fixed it. I think it was either a restricted rpc causing it or not actually flushing the mempool.

**Comment by moneroexamples** [comment]
Good to hear:-)
