### ISSUE TITLE
median block size is stuck on xmrchain.net

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#114]
I don't know why.

**Comment by moneroexamples** [comment]
You mean this one `(Median size of these blocks: 121.27 kB)` ? I see it changes? Or this one ` Median block size limit: 292.97 kB`?

**Comment by Gingeropolous** [comment]
the limit one

**Comment by moneroexamples** [comment]
this is maxium block size without penalty. It only changes when blocks are getting full. So have to observer when there is influx of txs and monero dynamic block algorithm kicks in.

**Comment by Gingeropolous** [comment]
i know.... it happened recently

**Comment by moneroexamples** [comment]
ah ok. so will look into it. 

btw, did you have a chance too consider running stagenet explorer and js for decoding txs for the explorer?

**Comment by Gingeropolous** [comment]
i thought our whole thing was being anti javascript.

yeah, just haven't gotten to it. i think I setup the stagenet daemon so it syncd and then i forgot... but at least its syncd.

**Comment by stoffu** [comment]
@Gingeropolous 
> i thought our whole thing was being anti javascript.

It's a tradeoff. Without JavaScript, the tx decoding can only be done server side, which means that the operator of the explorer gets to know and store all the view keys submitted by the users (which can be potentially abused later). Use of JavaScript may appear as undesirable, but it's the only way to perform the tx decoding completely client side on a browser.

**Comment by moneroexamples** [comment]
javascript support is optional and off by default. But when enabled, it provides decoding txs on the client side, so no viewkey is sent to server. So its something to consider if having no-javascript  is better than sending viewkey to server. 

Can test it first in testnet and/or stagenet explorer and see how it goes, if you would be interested in checking it out.

**Comment by moneroexamples** [comment]
Just for myself, so I dont forget: Can use this to check what sizes daemon is reporting.

'''
curl -X POST http://127.0.0.1:18081/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_info"}' -H 'Content-Type: application/json'
'''

**Comment by moneroexamples** [comment]
@Gingeropolous 

I think its correct. This block size limit will go up only if median size of 100 blocks is greater than full block reward size (300000 bytes). Few blocks greater than 300000 bytes won't affect the limit; it must be consistently larger. Thus I will add median size of 100 blocks to front page. Probably will replace current median size:

Transactions in the last 11 blocks
(Median size of these blocks: 65.94 kB) <--- this will be change to median of 100 blocks. Should be more in tune to what is happening with monero blocks.

**Comment by moneroexamples** [comment]
median of 100 blocks was added. Tentatively you can see how it looks: https://labor.serveo.net/

**Comment by moneroexamples** [comment]
I think the issue can be closed?
