### ISSUE TITLE
running make command

### ISSUE THREAD

**Issue by OwaisArain** [moneroexamples/onion-monero-blockchain-explorer#121]
Hello I am facing issue while running make command on monero directory.

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a: error adding symbols: Bad value collect2: error: ld returned 1 exit status tests/unit_tests/CMakeFiles/unit_tests.dir/build.make:1206: recipe for target 'tests/unit_tests/unit_tests' failed make[3]: * [tests/unit_tests/unit_tests] Error 1 make[3]: Leaving directory '/home/monero/build/release' CMakeFiles/Makefile2:4425: recipe for target 'tests/unit_tests/CMakeFiles/unit_tests.dir/all' failed make[2]: [tests/unit_tests/CMakeFiles/unit_tests.dir/all] Error 2 make[2]: Leaving directory '/home/monero/build/release' Makefile:138: recipe for target 'all' failed make1: [all] Error 2 make1: Leaving directory '/home/monero/build/release' Makefile:64: recipe for target 'release-all' failed make: * [release-all] Error 2

**Comment by moneroexamples** [comment]
Which OS and monero version? Also which branch of the explorer, master or devel?

**Comment by OwaisArain** [comment]
Ubuntu 16.4 monero v0.12.1.0 master branch

**Comment by stoffu** [comment]
Most likely this is due to insufficient amount of RAM. See https://github.com/monero-project/monero/blob/master/README.md#on-the-raspberry-pi and try increasing the swap size.

**Comment by OwaisArain** [comment]
Can you please guide me on how to install raspberry-pi ?

**Comment by stoffu** [comment]
Your question is too vague. Just follow Raspberry's official installation manual and then Monero's build instructions. Also, this repository is for the blockchain explorer. I suggest looking into https://monero.stackexchange.com/ for general FAQs.

**Comment by OwaisArain** [comment]
I have followed the steps and install the raspberry pi on a USB drive but now I don't know what to do for remainings? can you guide me how to work with it?

**Comment by stoffu** [comment]
Again, your question doesn't belong here. Check Q&A in https://monero.stackexchange.com/questions/tagged/raspberry-pi and if your problem still remains, ask a question there. Not here.

**Comment by OwaisArain** [comment]
Ok Thanks
