### ISSUE TITLE
Error when build the project

### ISSUE THREAD

**Issue by sajithaliyanage** [moneroexamples/onion-monero-blockchain-explorer#125]
when I compile the project it it gives me error as following

`Scanning dependencies of target myxrm
[  4%] Building CXX object src/CMakeFiles/myxrm.dir/MicroCore.cpp.o
/home/sajithaliyanage/Documents/private/Monerosci/parser/src/MicroCore.cpp: In member function ‘bool xmreg::MicroCore::init(const string&)’:
/home/sajithaliyanage/Documents/private/Monerosci/parser/src/MicroCore.cpp:91:59: error: no matching function for call to ‘cryptonote::Blockchain::init(cryptonote::BlockchainDB*&, cryptonote::HardFork*&, bool)’
     return m_blockchain_storage.init(db, m_hardfork, false);
                                                           ^
In file included from /home/sajithaliyanage/Documents/private/Monerosci/parser/src/monero_headers.h:26:0,
                 from /home/sajithaliyanage/Documents/private/Monerosci/parser/src/MicroCore.h:10,
                 from /home/sajithaliyanage/Documents/private/Monerosci/parser/src/MicroCore.cpp:5:
/home/sajithaliyanage/Documents/private/monero/src/cryptonote_core/blockchain.h:120:10: note: candidate: bool cryptonote::Blockchain::init(cryptonote::BlockchainDB*, cryptonote::network_type, bool, const cryptonote::test_options*)
     bool init(BlockchainDB* db, const network_type nettype = MAINNET, bool offline = false, const cryptonote::test_options *test_options = NULL);
          ^
/home/sajithaliyanage/Documents/private/monero/src/cryptonote_core/blockchain.h:120:10: note:   no known conversion for argument 2 from ‘cryptonote::HardFork*’ to ‘cryptonote::network_type’
In file included from /home/sajithaliyanage/Documents/private/Monerosci/parser/src/monero_headers.h:26:0,
                 from /home/sajithaliyanage/Documents/private/Monerosci/parser/src/MicroCore.h:10,
                 from /home/sajithaliyanage/Documents/private/Monerosci/parser/src/MicroCore.cpp:5:
/home/sajithaliyanage/Documents/private/monero/src/cryptonote_core/blockchain.h:132:10: note: candidate: bool cryptonote::Blockchain::init(cryptonote::BlockchainDB*, cryptonote::HardFork*&, cryptonote::network_type, bool)
     bool init(BlockchainDB* db, HardFork*& hf, const network_type nettype = MAINNET, bool offline = false);
          ^
/home/sajithaliyanage/Documents/private/monero/src/cryptonote_core/blockchain.h:132:10: note:   no known conversion for argument 3 from ‘bool’ to ‘cryptonote::network_type’
src/CMakeFiles/myxrm.dir/build.make:62: recipe for target 'src/CMakeFiles/myxrm.dir/MicroCore.cpp.o' failed
make[2]: *** [src/CMakeFiles/myxrm.dir/MicroCore.cpp.o] Error 1
CMakeFiles/Makefile2:254: recipe for target 'src/CMakeFiles/myxrm.dir/all' failed
make[1]: *** [src/CMakeFiles/myxrm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

I compile this with moner v0.11.1.0 branch tag.

**Comment by moneroexamples** [comment]
It will not compile against 0.11.1. You need 0.12.1.

**Comment by sajithaliyanage** [comment]
If I need to compile the project with v0.11.1.0 can you please tell me what would be the above issue? Because previously I compiled the project you have done with v0.11.1.0. It was work fine. Now I want to again compile the project as new one with same vesions.
