### ISSUE TITLE
How to get relevant input Txes when considering one output of another Tx 

### ISSUE THREAD

**Issue by sajithaliyanage** [moneroexamples/onion-monero-blockchain-explorer#127]
When gets two transactions Tx-a and Tx-b, let's assume there is a connection between these two transactions from Tx-a's one output is included in Tx-b's one input. How to get those? Is this feature enabled in this project? 

I saw in the explorer you have mapped Tx inputs ring members with relevant another Tx stealth-address. How you do that? Can you please explain this?

**Comment by moneroexamples** [comment]
You mean, when you click "more details" and get this for instance: https://xmrchain.net/tx/073d34f4ec75c09702d962d880d1d3af9fb0859e5e77aac5d331931e86465440/1 ?

Not sure what kind of explanation you need, but this is done here: https://github.com/moneroexamples/onion-monero-blockchain-explorer/blob/master/src/page.h#L5677

In short. You get absolute offsets of outputs used as ring members. You can use these offsets to get `tx_out_index` std::pair which will contain tx hash where the given output comes from. And once you have tx hash, you pull all sorts of data related to this tx.

**Comment by sajithaliyanage** [comment]
Yes, I meant above scenario. In existing tx data API, It doesn't give the offsets data of input ring members. and also outputs amount idx. Is there any way to get those data through  tx/<tx_hash> endpoint?

**Comment by moneroexamples** [comment]
You can get the offsets and amounts using rawtransaction json call, e.g.

 curl  -w "\n" -X GET "https://xmrchain.org/api/rawtransaction/6093260dbe79fd6277694d14789dc8718f1bd54457df8bab338c2efa3bb0f03d"

This can also be obtained from monero daemon's rpc:

curl -X POST http://127.0.0.1:18081/get_transactions -d '{"txs_hashes":["c1391f118b8f37aa284974a3b591621c6fd5219468dc13044cb0f2f27aa08786"], "decode_as_json": true}' -H 'Content-Type: application/json'

But entire information that is given by the explorer when you press `more details` is not available through json api. Probably I could add in near future if this is what you are after?

**Comment by sajithaliyanage** [comment]
Thank you very much for the above information. I suggest you to if you add all the information to the API, it would be useful for users. :+1:  

I have another problem. Can we convert **mstch::map construct_tx_context** function's return context to a json?

**Comment by moneroexamples** [comment]
> Can we convert mstch::map construct_tx_context function's return context to a json?

Yes, that would be probably the easiest way of doing this. 

I will add this call, and see how it goes. Should have something next week.

**Comment by sajithaliyanage** [comment]
Can you please explain me how can convert it? Because I just need all the data of inputs and outputs. If you can it would be a great help to me.

**Comment by moneroexamples** [comment]
I tentatively added `detailedtransaction`. Example result is here:

http://172.104.45.209:8081/api/detailedtransaction/f11b40d4f2fc030f793a8f579918deb7e2801cbfd5582bc5fd04857fe6289e12

If you have chrome with json formater, you should see pretty formatted json in your browsers.

**Comment by moneroexamples** [comment]
For now its in this PR: https://github.com/moneroexamples/onion-monero-blockchain-explorer/pull/130 to be marge later into `devel` branch. You can manually apply this patch to you clone of the repository if you want it now.

**Comment by sajithaliyanage** [comment]
Got it. Thanks mate! :+1: 

Another suggestion! Can you add an endpoint for this?
If someone gives an output's publick_key as a parameter, it gives all the input txes which contain it as input ring member?

Endpoint - https://domain.com/api/output-mixed-with/<public_key_of_output>
Results - {
           mixedTxData:[array of tx data]
}
