### ISSUE TITLE
Selecting interface to bind against

### ISSUE THREAD

**Issue by skftn** [moneroexamples/onion-monero-blockchain-explorer#128]
Feature request: Ability to change bind interface. Currently always defaults to `0.0.0.0`.

https://github.com/moneroexamples/onion-monero-blockchain-explorer/blob/5716416c25b9d6234da45829713578eb0b0c7fb8/main.cpp#L766-L775

I'd like to have nginx and/or varnish in front of the explorer. Currently, the only way to achieve this is to bind to `:81`, firewall that off and then proxypass to that.

Perhaps you could use this syntax: 

```c
app.bindaddr(app_host).port(app_port).multithreaded().run(); 
```
as shown [here](https://github.com/ipkn/crow/blob/b7360a2bacb426401636a1e76e5e713ed0c3b0fc/tests/unittest.cpp#L420) and then add a startup argument for bind host, say, `-x 127.0.0.1`.

If you don't have time I can look into it later, but not soon.

**Comment by moneroexamples** [comment]
Added. You can check it out now. `devel`  branch

https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/devel

If something, please let me know.
