### ISSUE TITLE
new mods break things

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#13]
(2016-11-24 03:23:38) [INFO    ] Request: 100.43.90.11:51051 0x7fb65c0047e0 HTTP/1.1 GET /block/557794
2016-Nov-23 22:23:40.166357 Exception: std::runtime_error
2016-Nov-23 22:23:40.166397 Unwinded call stack:
2016-Nov-23 22:23:40.167219      1                  0xc18850 __cxa_throw + 0x70
2016-Nov-23 22:23:40.167848      2                  0xc9bb52 date::init_tzdb() + 0x19c
2016-Nov-23 22:23:40.168522      3                  0xc9c5d7 date::get_tzdb() + 0x51
2016-Nov-23 22:23:40.169174      4                  0xc72d2a std::chrono::time_point<date::utc_clock, std::common_type<std::chrono::duration<long, std::ratio<1l, 1000000000l> >, std::chrono::duration<long, std::ratio<1l, 1l> > >::type> date::to_utc_time<std::chrono::duration<long, std::ratio<1l, 1000000000l> > >(std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > const&) + 0x27
2016-Nov-23 22:23:40.169828      5                  0xc6d06f xmreg::timestamp_to_str[abi:cxx11](long, char const*) + 0x4f
2016-Nov-23 22:23:40.170518      6                  0xa4189f xmreg::page::show_block[abi:cxx11](unsigned long) + 0x4e5

2016-Nov-23 22:23:40.171316      7                  0xa04403 main::{lambda(crow::request const&, unsigned long)#3}::operator()(crow::request co
nst&, unsigned long) const + 0x41
2016-Nov-23 22:23:40.172270      8                  0xa073d2 std::enable_if<(!crow::black_magic::CallHelper<main::{lambda(crow::request const&,
 unsigned long)#3}, std::enable_if::S<unsigned long> >::value)&&crow::black_magic<crow::black_magic::CallHelper, main::{lambda(crow::request co
nst&, unsigned long)#3}<crow::request, unsigned long> >::value, void>::type crow::TaggedRule<unsigned long>::operator()<main::{lambda(crow::req
uest const&, unsigned long)#3}>(crow::black_magic::CallHelper&&)::{lambda(crow::request const&, crow::response&, unsigned long)#1}::operator()(
crow::request const&, crow::response, unsigned long) const + 0x5a
2016-Nov-23 22:23:40.172965      9                  0xa09907 std::_Function_handler<void (crow::request const&, crow::response&, unsigned long)
, std::enable_if<(!crow::black_magic::CallHelper<main::{lambda(crow::request const&, unsigned long)#3}, std::enable_if::S<unsigned long> >::val
ue)&&crow::black_magic<crow::black_magic::CallHelper, main::{lambda(crow::request const&, unsigned long)#3}<crow::request, unsigned long> >::va
lue, void>::type crow::TaggedRule<unsigned long>::operator()<main::{lambda(crow::request const&, unsigned long)#3}>(crow::black_magic::CallHelp
er&&)::{lambda(crow::request const&, crow::response&, unsigned long)#1}>::_M_invoke(std::_Any_data const&, crow::request const&, crow::response
&, unsigned long&&) + 0x67
2016-Nov-23 22:23:40.173585     10                  0xb94c9c std::function<void (crow::request const&, crow::response&, unsigned long)>::operat
or()(crow::request const&, crow::response&, unsigned long) const + 0x76
2016-Nov-23 22:23:40.174239     11                  0xb9498c crow::detail::routing_handler_call_helper::call<crow::detail::routing_handler_call
_helper::call_params<std::function<void (crow::request const&, crow::response&, unsigned long)> >, 0, 1, 0, 0, crow::black_magic::S<>, crow::bl
ack_magic::S<crow::detail::routing_handler_call_helper::call_pair<unsigned long, 0> > >::operator()(crow::detail::routing_handler_call_helper::
call_params<std::function<void (crow::request const&, crow::response&, unsigned long)> >) + 0x34
2016-Nov-23 22:23:40.174944     12                  0xb94519 crow::detail::routing_handler_call_helper::call<crow::detail::routing_handler_call
_helper::call_params<std::function<void (crow::request const&, crow::response&, unsigned long)> >, 0, 0, 0, 0, crow::black_magic::S<unsigned lo
ng>, crow::black_magic::S<> >::operator()(crow::detail::routing_handler_call_helper::call_params<std::function<void (crow::request const&, crow
::response&, unsigned long)> >) + 0x33
2016-Nov-23 22:23:40.175570     13                  0xb93203 crow::TaggedRule<unsigned long>::handle(crow::request const&, crow::response&, cro
w::routing_params const&) + 0x63
2016-Nov-23 22:23:40.176239     14                  0xa1fe1b crow::Router::handle(crow::request const&, crow::response&) + 0x9bb
2016-Nov-23 22:23:40.177228     15                  0xb29cb5 crow::Crow<>::handle(crow::request const&, crow::response&) + 0x2f
2016-Nov-23 22:23:40.177966     16                  0xb1ae58 crow::Connection<crow::SocketAdaptor, crow::Crow<>>::handle() + 0x8d6
2016-Nov-23 22:23:40.178662     17                  0xb0d1ed crow::HTTPParser<crow::Connection<crow::SocketAdaptor, crow::Crow<>> >::process_me
ssage() + 0x1f
2016-Nov-23 22:23:40.179354     18                  0xaff328 crow::HTTPParser<crow::Connection<crow::SocketAdaptor, crow::Crow<>> >::on_message
_complete(http_parser*) + 0xf1
2016-Nov-23 22:23:40.184224     19                  0xa235d8 http_parser_execute + 0x2e2b
2016-Nov-23 22:23:40.184942     20                  0xaebd1a crow::HTTPParser<crow::Connection<crow::SocketAdaptor, crow::Crow<>> >::feed(char 
const*, int) + 0x2e
2016-Nov-23 22:23:40.185567     21                  0xad9c47 crow::Connection<crow::SocketAdaptor, crow::Crow<>>::do_read()::{lambda(boost::sys
tem::error_code const&, unsigned long)#1}::operator()(boost::system::error_code const&, unsigned long) const + 0x8d
2016-Nov-23 22:23:40.186265     22                  0xb41250 boost::asio::detail::binder2<crow::Connection<crow::SocketAdaptor, crow::Crow<>>::
do_read()::{lambda(boost::system::error_code const&, unsigned long)#1}, boost::system::error_code, unsigned long>::operator()() + 0x2e
2016-Nov-23 22:23:40.186938     23                  0xb3af6f void boost::asio::asio_handler_invoke<boost::asio::detail::binder2<crow::Connectio
n<crow::SocketAdaptor, crow::Crow<>>::do_read()::{lambda(boost::system::error_code const&, unsigned long)#1}, boost::system::error_code, unsign
ed long> >(boost::asio::detail::binder2<crow::Connection<crow::SocketAdaptor, crow::Crow<>>::do_read()::{lambda(boost::system::error_code const
&, unsigned long)#1}, boost::system::error_code, unsigned long>&, ...) + 0x68

2016-Nov-23 22:23:40.188264     25                  0xb29e17 boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, crow:
:Connection<crow::SocketAdaptor, crow::Crow<>>::do_read()::{lambda(boost::system::error_code const&, unsigned long)#1}>::do_complete(boost::asi
o::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) + 0xc8
2016-Nov-23 22:23:40.188925     26                  0xa125b0 boost::asio::detail::task_io_service_operation::complete(boost::asio::detail::task
_io_service&, boost::system::error_code const&, unsigned long) + 0x32
2016-Nov-23 22:23:40.189522     27                  0xa14a21 boost::asio::detail::epoll_reactor::descriptor_state::do_complete(boost::asio::det
ail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) + 0x63
2016-Nov-23 22:23:40.190197     28                  0xa125b0 boost::asio::detail::task_io_service_operation::complete(boost::asio::detail::task
_io_service&, boost::system::error_code const&, unsigned long) + 0x32
2016-Nov-23 22:23:40.190825     29                  0xa15877 boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lock<
boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&) + 0x1b7
2016-Nov-23 22:23:40.191447     30                  0xa1506d boost::asio::detail::task_io_service::run(boost::system::error_code&) + 0xf1
2016-Nov-23 22:23:40.192094     31                  0xa15b8e boost::asio::io_service::run() + 0x3e
2016-Nov-23 22:23:40.192711     32                  0xa94bf2 crow::Server<crow::Crow<>, crow::SocketAdaptor>::run()::{lambda()#1}::operator()()
 const + 0x272
2016-Nov-23 22:23:40.193473     33                  0xb5d264 void std::_Bind_simple<crow::Server<crow::Crow<>, crow::SocketAdaptor>::run()::{la
mbda()#1} ()>::_M_invoke<>(std::_Index_tuple<>) + 0x28
2016-Nov-23 22:23:40.194235     34                  0xb57202 std::_Bind_simple<crow::Server<crow::Crow<>, crow::SocketAdaptor>::run()::{lambda(
)#1} ()>::operator()() + 0x2c
2016-Nov-23 22:23:40.194928     35                  0xb5070c std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>
, std::__future_base::_Result_base::_Deleter>, std::_Bind_simple<crow::Server<crow::Crow<>, crow::SocketAdaptor>::run()::{lambda()#1} ()>, void
>::operator()() const + 0x30
2016-Nov-23 22:23:40.195605     36                  0xb4bfb1 std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__fu
ture_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::
_Result_base::_Deleter>, std::_Bind_simple<crow::Server<crow::Crow<>, crow::SocketAdaptor>::run()::{lambda()#1} ()>, void> >::_M_invoke(std::_A
ny_data const&) + 0x3d
2016-Nov-23 22:23:40.196292     37                  0xa5c5d2 std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base
::_Result_base::_Deleter> ()>::operator()() const + 0x4c
2016-Nov-23 22:23:40.197000     38                  0xa0ddf8 std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__
future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) + 0x36
2016-Nov-23 22:23:40.197719     39                  0xac775a void std::_Mem_fn_base<void (std::__future_base::_State_baseV2::*)(std::function<s
td::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), true>::operator()<std::function<std:
:unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*, void>(std::__future_base::_State_baseV2*
, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&) const + 0x94
2016-Nov-23 22:23:40.198501     40                  0xab32cd void std::_Bind_simple<std::_Mem_fn<void (std::__future_base::_State_baseV2::*)(st
d::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)> (std::__future_base::_S
tate_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)>::_M_inv
oke<0ul, 1ul, 2ul>(std::_Index_tuple<0ul, 1ul, 2ul>) + 0x7b
2016-Nov-23 22:23:40.199183     41                  0xa95920 std::_Bind_simple<std::_Mem_fn<void (std::__future_base::_State_baseV2::*)(std::fu
nction<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)> (std::__future_base::_State_
baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)>::operator()(
) + 0x2c

2016-Nov-23 22:23:40.199935     42                  0xa76333 void std::__once_call_impl<std::_Bind_simple<std::_Mem_fn<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)> (std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)> >() + 0x17
2016-Nov-23 22:23:40.200365     43                  0x7fb9f1668ae9 __pthread_once_slow + 0xa9
2016-Nov-23 22:23:40.201040     44                  0xa0383d __gthread_once(int*, void (*)()) + 0x31
2016-Nov-23 22:23:40.201693     45                  0xa5c45c void std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&) + 0xc1
2016-Nov-23 22:23:40.202330     46                  0xa0db76 std::__future_base::_State_baseV2::_M_set_result(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>, bool) + 0xa0
2016-Nov-23 22:23:40.203005     47                  0xb4030c std::__future_base::_Async_state_impl<std::_Bind_simple<crow::Server<crow::Crow<>, crow::SocketAdaptor>::run()::{lambda()#1} ()>, void>::_Async_state_impl(crow::Server<crow::Crow<>, crow::SocketAdaptor>::run()::{lambda()#1} (&&)())::{lambda()#1}::operator()() const + 0x72
2016-Nov-23 22:23:40.203616     48                  0xb9476e void std::_Bind_simple<std::__future_base::_Async_state_impl<std::_Bind_simple<crow::Server<crow::Crow<>, crow::SocketAdaptor>::run()::{lambda()#1} ()>, void>::_Async_state_impl(crow::Server<crow::Crow<>, crow::SocketAdaptor>::run()::{lambda()#1} (&&)())::{lambda()#1} ()>::_M_invoke<>(std::_Index_tuple<>) + 0x28
2016-Nov-23 22:23:40.204729     49                  0xb937aa std::_Bind_simple<std::__future_base::_Async_state_impl<std::_Bind_simple<crow::Server<crow::Crow<>, crow::SocketAdaptor>::run()::{lambda()#1} ()>, void>::_Async_state_impl(crow::Server<crow::Crow<>, crow::SocketAdaptor>::run()::{lambda()#1} (&&)())::{lambda()#1} ()>::operator()() + 0x2c
2016-Nov-23 22:23:40.205423     50                  0xb90e34 std::thread::_Impl<std::_Bind_simple<std::__future_base::_Async_state_impl<std::_Bind_simple<crow::Server<crow::Crow<>, crow::SocketAdaptor>::run()::{lambda()#1} ()>, void>::_Async_state_impl(crow::Server<crow::Crow<>, crow::SocketAdaptor>::run()::{lambda()#1} (&&)())::{lambda()#1} ()> >::_M_run() + 0x1c
2016-Nov-23 22:23:40.205911     51                  0x7fb9f0f06c80 std::this_thread::__sleep_for(std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >) + 0x70
2016-Nov-23 22:23:40.206338     52                  0x7fb9f166170a start_thread + 0xca
2016-Nov-23 22:23:40.206740     53                  0x7fb9f088282d clone + 0x6d
2016-Nov-23 22:23:40.207144     54                  0x0

(2016-11-24 03:23:40) [ERROR   ] An uncaught exception occurred: Timezone database version "2016j" did not install correctly to "/home/monero/Downloads/tzdata"

**Comment by moneroexamples** [comment]
Checking this now. By the way do you have curl installed?

**Comment by Gingeropolous** [comment]
```sudo apt install libcurl4-openssl-dev```

this one? yeah. Do i need sudo apt install curl ?

**Comment by moneroexamples** [comment]
I think curl it self also needs to be installed. I'm just checking it on clean ubuntu 16.04.

**Comment by Gingeropolous** [comment]
already installed. 

monero@moonbot:~$ sudo apt-get install curl
[sudo] password for monero: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.47.0-1ubuntu2.2).
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.

**Comment by Gingeropolous** [comment]
I also have to run the thing as sudo for some reason, so maybe its some weird permissions thing? But sudo should make it chop through everything, because it makes it a ninja. Hence, sudo.

**Comment by moneroexamples** [comment]
This is this date library I added to work with timestamps and timezones, in more efficent way than using boost: https://github.com/HowardHinnant/date

The date libary needs to download current information about all timezones and their offsets. So I'm checking on clean ubuntu what is needed for compilation.

**Comment by moneroexamples** [comment]
Could  you try the following:

Remove /home/monero/Downloads/tzdata . Maybe its not complete downoaded by the date library

and also make clean compilation of the explorer from the master.

**Comment by Gingeropolous** [comment]
HAH! Man I'm so sorry - it turns out I had no /home/monero/Downloads directory. I'm trying with the recent head anyway.

**Comment by Gingeropolous** [comment]
Yeop it works fine. Sorry for wasting your time :(

**Comment by moneroexamples** [comment]
Never waising time. Its always useful to try to solve problems like this. Glad it works now.
