### ISSUE TITLE
Aeon cannot find libraries?

### ISSUE THREAD

**Issue by DurinsMine** [moneroexamples/onion-monero-blockchain-explorer#132]
```
make[2]: *** No rule to make target 'Xmr_BLOCKS_LIBRARY-NOTFOUND', needed by 'aeonblocks'.  Stop.
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/aeonblocks.dir/all' failed
make[1]: *** [CMakeFiles/aeonblocks.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

This is error I get at 95% I am trying to build Aeon block explorer from suhz branch but they have no issues tab. Any chance anyone can help?

```
Scanning dependencies of target myxrm
[  5%] Building CXX object src/CMakeFiles/myxrm.dir/MicroCore.cpp.o
[ 10%] Building CXX object src/CMakeFiles/myxrm.dir/tools.cpp.o
[ 15%] Building CXX object src/CMakeFiles/myxrm.dir/CmdLineOptions.cpp.o
[ 20%] Building CXX object src/CMakeFiles/myxrm.dir/rpccalls.cpp.o
[ 25%] Building CXX object src/CMakeFiles/myxrm.dir/CurrentBlockchainStatus.cpp.o
[ 30%] Building CXX object src/CMakeFiles/myxrm.dir/MempoolStatus.cpp.o
[ 35%] Linking CXX static library libmyxrm.a
[ 35%] Built target myxrm
Scanning dependencies of target myext
[ 40%] Building CXX object ext/CMakeFiles/myext.dir/fmt/format.cc.o
[ 45%] Building CXX object ext/CMakeFiles/myext.dir/fmt/ostream.cc.o
[ 50%] Linking CXX static library libmyext.a
[ 50%] Built target myext
Scanning dependencies of target mstch
[ 55%] Building CXX object ext/mstch/src/CMakeFiles/mstch.dir/state/in_section.cpp.o
[ 60%] Building CXX object ext/mstch/src/CMakeFiles/mstch.dir/state/outside_section.cpp.o
[ 65%] Building CXX object ext/mstch/src/CMakeFiles/mstch.dir/mstch.cpp.o
[ 70%] Building CXX object ext/mstch/src/CMakeFiles/mstch.dir/render_context.cpp.o
[ 75%] Building CXX object ext/mstch/src/CMakeFiles/mstch.dir/template_type.cpp.o
[ 80%] Building CXX object ext/mstch/src/CMakeFiles/mstch.dir/token.cpp.o
[ 85%] Building CXX object ext/mstch/src/CMakeFiles/mstch.dir/utils.cpp.o
[ 90%] Linking CXX static library libmstch.a
[ 90%] Built target mstch
Scanning dependencies of target aeonblocks
[ 95%] Building CXX object CMakeFiles/aeonblocks.dir/main.cpp.o
make[2]: *** No rule to make target 'Xmr_BLOCKS_LIBRARY-NOTFOUND', needed by 'aeonblocks'.  Stop.
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/aeonblocks.dir/all' failed
make[1]: *** [CMakeFiles/aeonblocks.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2


```

**Comment by DurinsMine** [comment]
-- MONERO_DIR: ~/aeon
-- FindMonero Xmr_COMMON_LIBRARIES /home/pooldaemon/aeon/build/release/src/common/libcommon.a
**-- FindMonero Xmr_BLOCKS_LIBRARIES Xmr_BLOCKS_LIBRARY-NOTFOUND**
-- FindMonero Xmr_CRYPTONOTE_BASIC_LIBRARIES /home/pooldaemon/aeon/build/release/src/cryptonote_basic/libcryptonote_basic.a
-- FindMonero Xmr_CRYPTONOTE_CORE_LIBRARIES /home/pooldaemon/aeon/build/release/src/cryptonote_core/libcryptonote_core.a
-- FindMonero Xmr_CRYPTONOTE_PROTOCOL_LIBRARIES /home/pooldaemon/aeon/build/release/src/cryptonote_protocol/libcryptonote_protocol.a
-- FindMonero Xmr_DAEMONIZER_LIBRARIES /home/pooldaemon/aeon/build/release/src/daemonizer/libdaemonizer.a
-- FindMonero Xmr_MNEMONICS_LIBRARIES /home/pooldaemon/aeon/build/release/src/mnemonics/libmnemonics.a
-- FindMonero Xmr_EPEE_LIBRARIES /home/pooldaemon/aeon/build/release/contrib/epee/src/libepee.a
-- FindMonero Xmr_LMDB_LIBRARIES /home/pooldaemon/aeon/build/release/external/db_drivers/liblmdb/liblmdb.a
-- FindMonero Xmr_DEVICE_LIBRARIES /home/pooldaemon/aeon/build/release/src/device/libdevice.a
-- FindMonero Xmr_BLOCKCHAIN_DB_LIBRARIES /home/pooldaemon/aeon/build/release/src/blockchain_db/libblockchain_db.a
-- FindMonero Xmr_RINGCT_LIBRARIES /home/pooldaemon/aeon/build/release/src/ringct/libringct.a
-- FindMonero Xmr_WALLET_LIBRARIES /home/pooldaemon/aeon/build/release/lib/libwallet.a
-- FindMonero Xmr_CNCRYPTO_LIBRARIES /home/pooldaemon/aeon/build/release/src/crypto/libcncrypto.a
-- FindMonero Xmr_EASYLOGGING_LIBRARIES /home/pooldaemon/aeon/build/release/external/easylogging++/libeasylogging.a
-- FindMonero Xmr_VERSION_LIBRARIES /home/pooldaemon/aeon/build/release/src/libversion.a
-- FindMonero Xmr_CHECKPOINTS_LIBRARIES /home/pooldaemon/aeon/build/release/src/checkpoints/libcheckpoints.a

**Comment by moneroexamples** [comment]
Could you specify which Linux do you use and which aeon version (official release or latest master branch) you use? 

I ask because I just checked on Arch with latest aeon master branch and it compiles fine for me.

**Comment by moneroexamples** [comment]
No update on the issue. guess it can be closed?
