### ISSUE TITLE
Package 'pcsclite' is not linked when built against Monero since the addition of ledger hw compat

### ISSUE THREAD

**Issue by blur-network** [moneroexamples/onion-monero-blockchain-explorer#136]
The following error is output when attempting to build against XMR/BLUR code since pscslite became a required package for XMR. 

 `/build/release/src/device/libdevice.a(device_ledger.cpp.o): In function
 hw::ledger::device_ledger::exchange(unsigned int, unsigned int)':
 device_ledger.cpp:(.text+0x1aea): undefined reference to 'g_rgSCardT0Pci'
 device_ledger.cpp:(.text+0x1b0c): undefined reference to 'SCardTransmit'
 device_ledger.cpp:(.text+0x1f82): undefined reference to 'pcsc_stringify_error'
 device_ledger.cpp:(.text+0x1ffd): undefined reference to 'pcsc_stringify_error'
 /home/biz/Documents/GIT/WORK IN PROGRESS/blur/build/release/src/device
 /libdevice.a(device_ledger.cpp.o): In function 'hw::ledger::device_ledger::init()':
 device_ledger.cpp:(.text+0x25ae): undefined reference to 'SCardEstablishContext'
 device_ledger.cpp:(.text+0x266d): undefined reference to 'pcsc_stringify_error'
 device_ledger.cpp:(.text+0x26e7): undefined reference to 'pcsc_stringify_error'
 /libdevice.a(device_ledger.cpp.o): In function 'hw::ledger::device_ledger::connect()':
 device_ledger.cpp:(.text+0x2b4a): undefined reference to 'SCardListReaders'
 device_ledger.cpp:(.text+0x2c70): undefined reference to 'pcsc_stringify_error'
 device_ledger.cpp:(.text+0x2cee): undefined reference to 'pcsc_stringify_error'
 device_ledger.cpp:(.text+0x30a0): undefined reference to 'SCardFreeMemory'
 device_ledger.cpp:(.text+0x30c3): undefined reference to 'SCardDisconnect'
 device_ledger.cpp:(.text+0x3409): undefined reference to 'SCardConnect'
 device_ledger.cpp:(.text+0x358b): undefined reference to 'SCardStatus'
 device_ledger.cpp:(.text+0x38ea): undefined reference to 'SCardFreeMemory'
 collect2: error: ld returned 1 exit status
 CMakeFiles/xmrblocks.dir/build.make:135: recipe for target 'xmrblocks' failed
 make[2]: *** [xmrblocks] Error 1`

This is fixed by adding the flag `-lpcsclite` to the end of the command line located at: `CMakeFiles/xmrblocks.dir/link.txt `

**Comment by moneroexamples** [comment]
This should be already fixed in devel branch:

https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/devel
