### ISSUE TITLE
find_tx_extra_field_by_type does not take three parameters in 0.10.0

### ISSUE THREAD

**Issue by p4fg** [moneroexamples/onion-monero-blockchain-explorer#14]
find_tx_extra_field_by_type used in tools.cpp does not work with latest stable release of monero.

It only takes two parameters in the stable release.

**Comment by moneroexamples** [comment]
That's possible. Many things may not work with stable release of 10.0, because I'm preparying everything to be in sync with upcoming 10.1 release. Thus it is in sync with current development version. Sorry for this.

**Comment by moneroexamples** [comment]
If there are no further question, I will close this issue. Please feel free to re-open if needed.
