### ISSUE TITLE
With the last monero master i can't build the explorer

### ISSUE THREAD

**Issue by Onefox** [moneroexamples/onion-monero-blockchain-explorer#140]
I am getting the following error up on make:

I used the monero master on "91c7d68".

`root@odroid:~/onion-monero-blockchain-explorer/build# make
[  5%] Building CXX object src/CMakeFiles/myxrm.dir/tools.cpp.o
/root/onion-monero-blockchain-explorer/src/tools.cpp: In function 'std::__cxx11::string xmreg::decrypt(const string&, const secret_key&, bool)':
/root/onion-monero-blockchain-explorer/src/tools.cpp:1051:57: error: no matching function for call to 'generate_chacha_key(const secret_key*, long unsigned int, crypto::chacha_key&)'
     crypto::generate_chacha_key(&skey, sizeof(skey), key);
                                                         ^
In file included from /root/monero/src/serialization/crypto.h:37:0,
                 from /root/monero/src/cryptonote_basic/cryptonote_basic.h:44,
                 from /root/monero/src/cryptonote_basic/cryptonote_basic_impl.h:33,
                 from /root/monero/src/cryptonote_core/tx_pool.h:44,
                 from /root/onion-monero-blockchain-explorer/src/monero_headers.h:24,
                 from /root/onion-monero-blockchain-explorer/src/tools.h:18,
                 from /root/onion-monero-blockchain-explorer/src/tools.cpp:5:
/root/monero/src/crypto/chacha.h:73:15: note: candidate: void crypto::generate_chacha_key(const void*, size_t, crypto::chacha_key&, uint64_t)
   inline void generate_chacha_key(const void *data, size_t size, chacha_key& key, uint64_t kdf_rounds) {
               ^~~~~~~~~~~~~~~~~~~
/root/monero/src/crypto/chacha.h:73:15: note:   candidate expects 4 arguments, 3 provided
/root/monero/src/crypto/chacha.h:91:15: note: candidate: void crypto::generate_chacha_key(std::__cxx11::string, crypto::chacha_key&, uint64_t)
   inline void generate_chacha_key(std::string password, chacha_key& key, uint64_t kdf_rounds) {
               ^~~~~~~~~~~~~~~~~~~
/root/monero/src/crypto/chacha.h:91:15: note:   no known conversion for argument 1 from 'const secret_key* {aka const epee::mlocked<tools::scrubbed<crypto::ec_scalar> >*}' to 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}'
src/CMakeFiles/myxrm.dir/build.make:86: recipe for target 'src/CMakeFiles/myxrm.dir/tools.cpp.o' failed
make[2]: *** [src/CMakeFiles/myxrm.dir/tools.cpp.o] Error 1
CMakeFiles/Makefile2:254: recipe for target 'src/CMakeFiles/myxrm.dir/all' failed
make[1]: *** [src/CMakeFiles/myxrm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by Onefox** [comment]
Looks like the function signature has changed and a new argument needs to be added just as in the PR here:
https://github.com/monero-project/monero/pull/4272/files


I changed the function call in the tools.cpp file and added the 1 there... now its building.

**Comment by Onefox** [comment]
And I am at the next error:

`[ 95%] Linking CXX executable xmrblocks
/root/monero/build/release/src/ringct/libringct_basic.a(bulletproofs.cc.o): In function `rct::bulletproof_VERIFY(rct::Bulletproof const&)':
bulletproofs.cc:(.text+0x9b34): undefined reference to `crypto_verify_32'
bulletproofs.cc:(.text+0xa438): undefined reference to `crypto_verify_32'
/root/monero/build/release/src/cryptonote_core/libcryptonote_core.a(blockchain.cpp.o): In function `cryptonote::Blockchain::check_tx_inputs(cryptonote::transaction&, cryptonote::tx_verification_context&, unsigned long*)':
blockchain.cpp:(.text+0xfb38): undefined reference to `crypto_verify_32'
blockchain.cpp:(.text+0xfb8c): undefined reference to `crypto_verify_32'
blockchain.cpp:(.text+0x11218): undefined reference to `crypto_verify_32'
/root/monero/build/release/src/cryptonote_core/libcryptonote_core.a(blockchain.cpp.o):blockchain.cpp:(.text+0x11268): more undefined references to `crypto_verify_32' follow
CMakeFiles/xmrblocks.dir/main.cpp.o: In function `xmreg::page::index2[abi:cxx11](unsigned long, bool)':
main.cpp:(.text._ZN5xmreg4page6index2B5cxx11Emb[_ZN5xmreg4page6index2B5cxx11Emb]+0x9a0): undefined reference to `bool cryptonote::Blockchain::get_transactions<std::vector<crypto::hash, std::allocator<crypto::hash> >, std::__cxx11::list<cryptonote::transaction, std::allocator<cryptonote::transaction> >, std::__cxx11::list<crypto::hash, std::allocator<crypto::hash> > >(std::vector<crypto::hash, std::allocator<crypto::hash> > const&, std::__cxx11::list<cryptonote::transaction, std::allocator<cryptonote::transaction> >&, std::__cxx11::list<crypto::hash, std::allocator<crypto::hash> >&) const'
CMakeFiles/xmrblocks.dir/main.cpp.o: In function `xmreg::page::json_transactions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
main.cpp:(.text._ZN5xmreg4page17json_transactionsENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_[_ZN5xmreg4page17json_transactionsENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_]+0x880): undefined reference to `bool cryptonote::Blockchain::get_transactions<std::vector<crypto::hash, std::allocator<crypto::hash> >, std::__cxx11::list<cryptonote::transaction, std::allocator<cryptonote::transaction> >, std::__cxx11::list<crypto::hash, std::allocator<crypto::hash> > >(std::vector<crypto::hash, std::allocator<crypto::hash> > const&, std::__cxx11::list<cryptonote::transaction, std::allocator<cryptonote::transaction> >&, std::__cxx11::list<crypto::hash, std::allocator<crypto::hash> >&) const'
CMakeFiles/xmrblocks.dir/main.cpp.o: In function `xmreg::page::json_outputsblocks(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)':
main.cpp:(.text._ZN5xmreg4page18json_outputsblocksENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_S6_b[_ZN5xmreg4page18json_outputsblocksENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_S6_b]+0x8d8): undefined reference to `bool cryptonote::Blockchain::get_transactions<std::vector<crypto::hash, std::allocator<crypto::hash> >, std::__cxx11::list<cryptonote::transaction, std::allocator<cryptonote::transaction> >, std::__cxx11::list<crypto::hash, std::allocator<crypto::hash> > >(std::vector<crypto::hash, std::allocator<crypto::hash> > const&, std::__cxx11::list<cryptonote::transaction, std::allocator<cryptonote::transaction> >&, std::__cxx11::list<crypto::hash, std::allocator<crypto::hash> >&) const'
src/libmyxrm.a(MicroCore.cpp.o): In function `xmreg::MicroCore::get_tx_hash_from_output_pubkey(crypto::public_key const&, unsigned long const&, crypto::hash&, cryptonote::transaction&)':
MicroCore.cpp:(.text+0xed8): undefined reference to `bool cryptonote::Blockchain::get_transactions<std::vector<crypto::hash, std::allocator<crypto::hash> >, std::__cxx11::list<cryptonote::transaction, std::allocator<cryptonote::transaction> >, std::__cxx11::list<crypto::hash, std::allocator<crypto::hash> > >(std::vector<crypto::hash, std::allocator<crypto::hash> > const&, std::__cxx11::list<cryptonote::transaction, std::allocator<cryptonote::transaction> >&, std::__cxx11::list<crypto::hash, std::allocator<crypto::hash> >&) const'
src/libmyxrm.a(CurrentBlockchainStatus.cpp.o): In function `xmreg::CurrentBlockchainStatus::calculate_emission_in_blocks(unsigned long, unsigned long)':
CurrentBlockchainStatus.cpp:(.text+0xaa8): undefined reference to `bool cryptonote::Blockchain::get_transactions<std::vector<crypto::hash, std::allocator<crypto::hash> >, std::__cxx11::list<cryptonote::transaction, std::allocator<cryptonote::transaction> >, std::__cxx11::list<crypto::hash, std::allocator<crypto::hash> > >(std::vector<crypto::hash, std::allocator<crypto::hash> > const&, std::__cxx11::list<cryptonote::transaction, std::allocator<cryptonote::transaction> >&, std::__cxx11::list<crypto::hash, std::allocator<crypto::hash> >&) const'
collect2: error: ld returned 1 exit status
CMakeFiles/xmrblocks.dir/build.make:133: recipe for target 'xmrblocks' failed
make[2]: *** [xmrblocks] Error 1
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/xmrblocks.dir/all' failed
make[1]: *** [CMakeFiles/xmrblocks.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by moneroexamples** [comment]
Use devel branch of the explorer:

https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/devel

master branch of the explorer will not compile with the current monero master branch.

**Comment by Onefox** [comment]
Thanks it worked with the branch
