### ISSUE TITLE
Crash if the blockchain has less than 50 blocks

### ISSUE THREAD

**Issue by Onefox** [moneroexamples/onion-monero-blockchain-explorer#141]
My private net has around 35 blocks, after I call the the page I get the following server output:
`root@odroid:~/onion-monero-blockchain-explorer/build# sleep 3 && cd ~/onion-monero-blockchain-explorer/build && ./xmrblx
ocks -t -p 9999 -b ~/testnet/node_01/testnet/lmdb/ --no-blocks-on-index 50 --enable-as-hex  --enable-pusher            x
2018-09-02 15:06:04,474 INFO  [default] Page size: 4096                                                                x
"/root/testnet/node_01/testnet/lmdb"                                                                                   x
Staring in non-ssl mode                                                                                                x
(2018-09-02 15:06:04) [INFO    ] Crow/0.1 server is running at 0.0.0.0:9999 using 4 threads                            x
(2018-09-02 15:06:04) [INFO    ] Call `app.loglevel(crow::LogLevel::Warning)` to hide Info level logs.                 x
Current network info read, mempool status txs: 0                                                                       x
mempool status txs: 0                                                                                                  x
mempool status txs: 0                                                                                                  x
mempool status txs: 0                                                                                                  x
mempool status txs: 0                                                                                                  x
(2018-09-02 15:06:29) [INFO    ] Request: 192.168.178.22:56605 0x55736dd910 HTTP/1.1 GET /                             x
2018-09-02 15:06:29.351       7f6b7fdd20        WARN    blockchain.db.lmdb      src/blockchain_db/lmdb/db_lmdb.cpp:75 Ax
ttempt to get block from height 50 failed -- block not in db                                                           x
terminate called after throwing an instance of 'cryptonote::BLOCK_DNE'                                                 x
terminate called recursively                                                                                           x
Aborted                                                                                                                x
root@odroid:~/onion-monero-blockchain-explorer/build#       `

**Comment by moneroexamples** [comment]
Thx.

Should be just fixed https://github.com/moneroexamples/onion-monero-blockchain-explorer/commit/5fea46c28a99f82fd3a23d651b46c21d09fa6c47 in devel branch:

https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/devel

**Comment by Onefox** [comment]
Working now thanks a lot!
