### ISSUE TITLE
Can't open the last block in the view

### ISSUE THREAD

**Issue by Onefox** [moneroexamples/onion-monero-blockchain-explorer#145]
I have a private testnet with 72 blocks. When I try to view the last block 71 the explorer crashes.
Could it be that something in the monero api changed with the index?

I am running:
explorer version (api): devel-2018-09-03-5fea46c (1.1) | monero version: 0.12.3.0-master-91c7d68b

The console log is:
Getting mempool failed                                                                     
(2018-09-17 21:14:52) [INFO    ] Request: 192.168.178.22:58829 0x7f2c003600 HTTP/1.1 GET /block/71
2018-09-17 21:14:52.449       7f4dbe0d20        WARN    blockchain.db.lmdb      src/blockchain_db/lmdb/db_lmdb.cpp:75      Attempt to get hash from height 72 failed -- hash not in db
terminate called after throwing an instance of 'cryptonote::BLOCK_DNE'
terminate called recursively
Aborted

**Comment by moneroexamples** [comment]
Do you use current mater or devel branch of monero? 

This issue was reported for devel branch and was solved there as well, unless its something new:
https://github.com/moneroexamples/onion-monero-blockchain-explorer/issues/141

**Comment by Onefox** [comment]
This is something new, I closed the #141.

I used: explorer version (api): devel-2018-09-03-5fea46c (1.1) | monero version: 0.12.3.0-master-91c7d68b

So Master on monero 91c7d68b from a little while ago and devel 5fea46c from onion-monero-blockchain-explorer.

Or what do you mean?

**Comment by moneroexamples** [comment]
Thank's for details. I will look into it and let you know once I make any progress.

**Comment by moneroexamples** [comment]
Could you run it through `gdb` and get the backtrace where it crashes? 

You can run explorer trough gdb as follows (example):

```
gdb --args ./xmrblocks list-of_your_arguments
```
then start it using `run` inside gdb.

use it till it crashes and there `where` or `bt` should show the chain of execution to the code which crashed?

**Comment by moneroexamples** [comment]
Unfortunately I cant replicate your problem, even using your private blockchain. Everything seems to work fine for me. 

> I could not access the page at all after runing it with gdb.

Did you execute `run` command after entertaining gdb environment?

**Comment by Onefox** [comment]
yes i did.
I get ERR_CONNECTION_REFUSED.
After I run it like this:


`gdb --args ./xmrblocks -t -p 9999 -b ~/testnet/node_01/testnet/lmdb/ --no-blocks-on-index 50 --enable-as-hex  --enable-pusher
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./xmrblocks...done.
(gdb) run
Starting program: /root/onion-monero-blockchain-explorer/build/xmrblocks -t -p 9999 -b /root/testnet/node_01/testnet/lmdb/ --no-blocks-on-index 50 --enable-as-hex --enable-pusher
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x0000007fb7aa83a8 in ?? () from /usr/lib/aarch64-linux-gnu/libcrypto.so.1.1
(gdb)
`

**Comment by moneroexamples** [comment]
Explorer crashes immediately in your case when you run in gdb. DI don't know what is happening. I run it with your private blockchain and had no issues.

You can try running latest explorer from devel branch. For this you will need to upgrade your monero as well as the explorer will not compile with your monero version. It will be also easier for me as we will be using same versions of monero and the explorer, rather than older versions.

If you upgrade your monero, please not that compilation procedure changed. Now need to use `
USE_SINGLE_BUILDDIR=1 make` because monero change the structure of its build folders.

**Comment by Onefox** [comment]
It didn't crashes without gdb immediately, I could still explore other blocks i will try with the new build

**Comment by moneroexamples** [comment]
Wonder if there are any updates this this issue?

**Comment by Onefox** [comment]
The problem is, I cant build monero on my system anymore...

**Comment by moneroexamples** [comment]
Did you make issue that monero does not compile?

**Comment by Onefox** [comment]
Looks like it got another response there, I will give It another go when I find the time.
Here is the link for reference
https://github.com/monero-project/monero/issues/4452
