### ISSUE TITLE
Incorrect Fee per KB Estimation

### ISSUE THREAD

**Issue by vtnerd** [moneroexamples/onion-monero-blockchain-explorer#150]
The fee per KB estimation is incorrect on testnet, and will be incorrect on mainnet after next fork. The API suddenly changed to return per byte. Yeah I know, looking into cleanup of the fee stuff in `monerod` somehow, but it won't happen for a while ...

**Comment by moneroexamples** [comment]
I noticed few days ago that there were some fee changes, but was not sure what's happening. OpenMonero also has problem due to fee issue:
https://github.com/moneroexamples/openmonero/issues/100

Thanks for the info.

**Comment by moneroexamples** [comment]
I think its resolved.
