### ISSUE TITLE
txpool: Failed to parse transaction from blob

### ISSUE THREAD

**Issue by moneroexamples** [moneroexamples/onion-monero-blockchain-explorer#152]
Getting the error:

```
Cant make tx from _tx_info.tx_blob
2018-10-21 08:38:28.953	    7feca9569700	ERROR	cn	src/cryptonote_basic/cryptonote_format_utils.cpp:218	Failed to parse transaction from blob
```

**Comment by moneroexamples** [comment]
https://github.com/moneroexamples/onion-monero-blockchain-explorer/commit/afd168cd6c567b034b3f4f2d3031be9ad3e3a09a

Closing for now. Please feel free to reopen if problem persists.

**Comment by SergeyAnkarenko** [comment]
Thanks, 

Will it work, if I apply the same change to https://github.com/moneroexamples/openmonero/blob/fc88d67fffffcce9a8b3bf46d36167890b8a8da6/src/CurrentBlockchainStatus.cpp#L475 as it described in the https://github.com/moneroexamples/onion-monero-blockchain-explorer/commit/afd168cd6c567b034b3f4f2d3031be9ad3e3a09a commit
