### ISSUE TITLE
No rule to make target 'Xmr_WALLET_LIBRARY-NOTFOUND

### ISSUE THREAD

**Issue by sonicskye** [moneroexamples/onion-monero-blockchain-explorer#153]
Hi,
I am trying to compile the latest version on Ubuntu 18.04.1, but it failed. 

[ 95%] Building CXX object CMakeFiles/xmrblocks.dir/main.cpp.o
make[2]: *** No rule to make target 'Xmr_WALLET_LIBRARY-NOTFOUND', needed by 'xmrblocks'.  Stop.
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/xmrblocks.dir/all' failed
make[1]: *** [CMakeFiles/xmrblocks.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I tried multiple times, including re-downloading the source, but the problem persists.

**Comment by moneroexamples** [comment]
Did you build monero using `USE_SINGLE_BUILDDIR=1 make` instead of just `make`?

Monero bulld instruction for the explorer are here for reference: https://github.com/moneroexamples/onion-monero-blockchain-explorer#compile-latest-monero-version-013

**Comment by sonicskye** [comment]
Uh, no I missed that part.
After recompiling the monero, the error is gone. Thank you.
