### ISSUE TITLE
i cant get the monero version to display correctly

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#154]
where the hell is that string? ima just do it manually. no idea why it isn';t updating. I built master of both repos. still showing v0.12

**Comment by moneroexamples** [comment]
Its in footer.html: https://github.com/moneroexamples/onion-monero-blockchain-explorer/blob/master/src/templates/footer.html

Usually I wipe the the explorer's build folder entirely before compiling it again. Sometimes staff gets cached due to cmake.

**Comment by moneroexamples** [comment]
Since there are no new updates, I guess its fine to close the issue.?
