### ISSUE TITLE
is tx extra supposed to be like this?

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#155]
https://xmrchain.net/tx/2251b45a4b9e43b565e76584c3a906c9203058c44ee5787be0cf86f5a8fe2b65

**Comment by moneroexamples** [comment]
It should not. It is showing details view by default. Don't know why. The latest explorer build looks like this: http://172.104.45.209:8081/ where this issue does not appear.

Do you enable any caches in the explorer? If so, could you run explorer without them, and see?

**Comment by Gingeropolous** [comment]
i was running 

--enable-tx-cache 1 \
--enable-block-cache 1 \


also, i tried compiling your master and monero v013.0.4 ..., so xmrblocks was made against v013.0.4. the explorer got stuck. The mempool kept filling but the blocks weren't updating. I think I was using Monero 'Beryllium Bullet' (v0.13.0.2-release). 

So xmrblocks from your master using 13.0.4 and a monerod from 13.0.2 ....

i had to revert to the old xmrblocks bin I had (which was working). When I did that, xmrblocks starting popping blocks. Was it popping its own database?

Or it could have been 0.13.0.2 had frozen, because i stopped and started monerod and it caught up. 

ultimately, it seems a lot of crazy stuff just happened. I'll try running the updated stuff again soon.

**Comment by moneroexamples** [comment]
There were some issues in monero with tx pool in monero (https://github.com/monero-project/monero/pull/4635) very recently, and the explorer had also issues to this. Could be an explanation what's happening for you if you run litter older monerod. 

I would try with 0.13.0.4, and see how it goes. 

I would disable caches (--enable-tx-cache 1 --enable-block-cache 1 \) as well. I discussed this before with hyc and its better to have lmdb take care of caching, instead of double caching with the explorer. 

Not sure about popping blocks though. 

yes, v9 brought so many changes in its C++ codebase, that its difficult to wrap ones head about all of them.

**Comment by stoffu** [comment]
The tx extra 
```
0157026f73a9e03699060fec18ce2092ff02126443226e6435b00c12014369b49c0410c86c15ce5e9eddc9e6753dd9f4cee671649773280dd504e6f5e2ee52c7e463293245d5c65e15181837ceafa3d4aadfaa906617431ddc1b354596f723fe9a001641beb1a405955b6b500d856612166ee0d5114e44dc09b2c42c7f1ae2a41648fd3541439ce768ab4aab1fb918b3d3775ed528c635474c22621e168ccf36df5bf97ab502cb706a2a6e7448b5622b629a62d4672c9f41410b61c53e5aecd16c02de2d87f7dca48b32b1d55eb8749d14b35353b07484fea2fbb0731faae51980a074a306b47138f9f6e46faae0c9f1f920af4348e6331ddc719dc3fa6922d90be1b5c03bd8c3ec3337eb09c1597d43edf2de42905f940c112202c8832b0fb05277352a24e3fa554807ebece223a99ae4c1519b2ad4fd0f2bf1b06c5b6d767ef227cce4725b87f17080a0480074ff794852d0f967bf5691d039a6752da30bef9ca2bf710fd32290f89cd6f3063e2f3fe65c17b90967521438bf3dec7b4ccc7eec730f226070070193f922dba5e16fc3fa624a2a19f77486893aaee64bcb03a07bb3975fb8dcafd02780f0e2f2bc5481ebecfbeec1d4490bd74b894dfd866c80d7699dc0799825a449d326190b76d6847843a970f38d995cead040a75c5836f854a5694a4eb6fb63435385bcd3a8947eb6fb0a6b6723d76ca4a29db6d0228e02260a616e5cd1f36d7f0415232d6a04758b5a847f04d6160bd6a4266d4d4cf38d026008
```
consists of one tx public key
```
01      // #define TX_EXTRA_TAG_PUBKEY                 0x01
57026f73a9e03699060fec18ce2092ff02126443226e6435b00c12014369b49c
```

and 16 additional tx public keys due to one or more of the 16 destinations being subaddress:
```
04    // #define TX_EXTRA_TAG_ADDITIONAL_PUBKEYS     0x04
10
c86c15ce5e9eddc9e6753dd9f4cee671649773280dd504e6f5e2ee52c7e46329
3245d5c65e15181837ceafa3d4aadfaa906617431ddc1b354596f723fe9a0016
41beb1a405955b6b500d856612166ee0d5114e44dc09b2c42c7f1ae2a41648fd
3541439ce768ab4aab1fb918b3d3775ed528c635474c22621e168ccf36df5bf9
7ab502cb706a2a6e7448b5622b629a62d4672c9f41410b61c53e5aecd16c02de
2d87f7dca48b32b1d55eb8749d14b35353b07484fea2fbb0731faae51980a074
a306b47138f9f6e46faae0c9f1f920af4348e6331ddc719dc3fa6922d90be1b5
c03bd8c3ec3337eb09c1597d43edf2de42905f940c112202c8832b0fb0527735
2a24e3fa554807ebece223a99ae4c1519b2ad4fd0f2bf1b06c5b6d767ef227cc
e4725b87f17080a0480074ff794852d0f967bf5691d039a6752da30bef9ca2bf
710fd32290f89cd6f3063e2f3fe65c17b90967521438bf3dec7b4ccc7eec730f
226070070193f922dba5e16fc3fa624a2a19f77486893aaee64bcb03a07bb397
5fb8dcafd02780f0e2f2bc5481ebecfbeec1d4490bd74b894dfd866c80d7699d
c0799825a449d326190b76d6847843a970f38d995cead040a75c5836f854a569
4a4eb6fb63435385bcd3a8947eb6fb0a6b6723d76ca4a29db6d0228e02260a61
6e5cd1f36d7f0415232d6a04758b5a847f04d6160bd6a4266d4d4cf38d026008
```

**Comment by moneroexamples** [comment]
I guess the issue can be closed?
