### ISSUE TITLE
You guys are on the outdated chain still

### ISSUE THREAD

**Issue by dginovker** [moneroexamples/onion-monero-blockchain-explorer#158]
Monero forked on October 17th to CryptoNote v9 and you guys are still using the 0.12 binaries which correlate to CN v7. Are you planning to update?

**Comment by moneroexamples** [comment]
the explorer will not even compile with 0.12. Where did you get the idea that its still using 0.12?

**Comment by dginovker** [comment]
Oh you know what.. There's another site that's not yours that's linking to your git repo and they're on the wrong chain.
