### ISSUE TITLE
mixin appears as 0 in the mempool

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#16]

**Comment by Gingeropolous** [comment]
I might need to copy the newly compiled static libraries and then recompile the block explorer. I'm using the recent master of monerod and no idea when I last copied the libraries over for compiling the block explorer.

**Comment by moneroexamples** [comment]
Current commit fixes the mixin problem: https://github.com/moneroexamples/onion-monero-blockchain-explorer/commit/7d27c26962e8bff4b259abfc06716c95e86cd08a 

Maybe it would be good idea to update monero itself. One reason is that I removed dependency of the explorer on custom patching for the mempool. Explorer works now with mempool as it is provided by unpatched monerod.
