### ISSUE TITLE
HTML not working in some browsers

### ISSUE THREAD

**Issue by jarole** [moneroexamples/onion-monero-blockchain-explorer#160]
Hi. during testing I noticed that some browsers display the explorer site as text with all the HTML code, so the site is not displayed as expected. The only browsers where the HTML is working are Firefox based (FF, Tor browser..) and lynx. "Bad browsers" (tested by me) are chrome/chromium , opera, brave, links...

command:
`links http://localhost:8081`

result:
```

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">
    <title>Onion Monero Blockchain Explorer</title>
    <!--<link rel="stylesheet" type="text/css" href="/css/style.css">-->
    <style type="text/css">
body {
    margin: 0;
    padding: 0;
    color: white;
    background-color: black;
}

h1, h2, h3, h4, h5, h6 {
    text-align: center;
}
...
```
Do you have similar problems with chrome or opera? 

Maybe Hint? 
I tried to save the site from browser to notebook and the saved file has no extension. When I rename the file to file.html, the HTML code is working even in chrome . Seems like some browsers are not able to recognize that it is HTML site (perhaps because of missing extension). Do you have any idea?

**Comment by moneroexamples** [comment]
Strange. Do you run it yourself, or use for example https://www.xmrchain.net where this issue occurs?

**Comment by jarole** [comment]
Thanks for the feedback.   https://www.xmrchain.net is working fine Yes, I run it myself.
Perhaps bad compilation within my env.  I will try to recompile.
Since we can't reproduce the problem, I am closing this issue .

**Comment by jarole** [comment]
Hello, 
I would reopen this issue , because I have not solved the issue so far.
OMBE has been installed (compiled) in standard way, and everything works fine. In Firefox ( and FF based browsers only).
Opera, Chrome display HTML code instead. 
Please have a look at [https://exp.xmr.sk](https://exp.xmr.sk) . I don't understand what could cause this problem. The issue persists in more versions.

**Comment by moneroexamples** [comment]
I see your instance has this problem on chrome. Its interesting indeed. I cant reproduce it. I also checked some other instances (https://github.com/moneroexamples/onion-monero-blockchain-explorer#explorer-hosts) and they all seem fine. 

I see you have ssl enabled. Also it seems you use cloadflair.  Does this also happen when you just use plain http on localhost?

**Comment by jarole** [comment]
Yes, the same on localhost. I have checked to exclude webserver as the reason.

-------- Original Message --------

**Comment by moneroexamples** [comment]
At the moment I dont know what could be the reason. Now I just noticed that the page is recognized in chrome as "Skencil document" when I wanted to save it as html (https://i.imgur.com/6d247Ll.png) It does not happen in other instances.

**Comment by moneroexamples** [comment]
I think I know what's happening. Chrome must be thinking that your instance is Skencil document due to *sk domain. Skencil files have sk extension. Obviously this is wrong. I also noticed that a `text/html` header is missing (https://imgur.com/ohNOHIE), thus chrome does not know it should render it is html. I have yet to check if the header is not provided by the explorer itself or there is some misconfiguration on your instance.

**Comment by jarole** [comment]
Thank you. Good point. 
Misconfiguration of my environment is also possible , but I have successfully reproduced the issue on clean install of Ubuntu on Azure few month ago.
I think it is not because of `.sk` domain, because it doesn't explain the issues on `localhost` or `.onion`

**Comment by moneroexamples** [comment]
I added `Content-Type", "text/html; charset=utf-8"` for the index page only just to see it it changes anything. You can check if this makes any difference. 

The change is in `devel` branch: https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/devel  Thus if you could compile it and check if there is any improvement. When checking please remember to hard refresh it, so that non-cached versions of the page are used.

**Comment by jarole** [comment]
Thanks friend, it works! 
Index is fine, but I think this patch will need also transactions sites, block sites...
Example:
https://exp.xmr.sk/tx/3fe115c585b2090af3fea5252e7042aeb6ecb9aafd369c8d600b83e353ab4720
https://exp.xmr.sk/block/1789438

**Comment by moneroexamples** [comment]
the header has been added to other pages. Updated version is in `devel` branch. You can have a look how it works now.

**Comment by jarole** [comment]
Thank you so much.

**Comment by moneroexamples** [comment]
No problem. Hope it will work fine now. 


p.s. Can I add your explorer to the list here: https://github.com/moneroexamples/onion-monero-blockchain-explorer#explorer-hosts ?

**Comment by jarole** [comment]
Yes, it works like a charm and yes you can add my instance to the list. I had a maintenance restart but now the service is running.
Thanks again, good job!
