### ISSUE TITLE
Trouble decoding outputs on v0.14.0.0 (stagenet)

### ISSUE THREAD

**Issue by lalvarezguillen** [moneroexamples/onion-monero-blockchain-explorer#167]
Hi.

After upgrading my stagenet node to `v0.14.0.0`, this Blockchain Explorer shows the amount of every output as zero. Publicly hosted Blockchain Explorers on the v10 protocol appear to be suffering from the same issue.

Take a look at the response of :

- https://stagenet.xmrchain.net/api/outputs?txhash=5d7020f5c6e0bce1b74949d664b47da6e6a8022217756e280e83092ba1695308&address=73LByqK36eLKLgU5y6dLBTMtXsa9LXnPKU4Q9H38T33nLr8FYRU3xy2XtqzgBRTuNG1qcRGmo818iBvrSB9Hz883CFohNJj&viewkey=3962197fb77a6d00a181d2a65ab7db32f90246bba10a2e75fce75ab37ff40c00

- http://162.210.173.150:8083/api/outputs?txhash=5d7020f5c6e0bce1b74949d664b47da6e6a8022217756e280e83092ba1695308&address=73LByqK36eLKLgU5y6dLBTMtXsa9LXnPKU4Q9H38T33nLr8FYRU3xy2XtqzgBRTuNG1qcRGmo818iBvrSB9Hz883CFohNJj&viewkey=3962197fb77a6d00a181d2a65ab7db32f90246bba10a2e75fce75ab37ff40c00

```json
{
  "data": {
    "address": "1ca6b99bc83d996da4c4528a02f77a7ce254d6d4be6182a1c5d79ed84892a976a848a352dafd2db8b3d10cec41ea310502c14457a045f7415650374e8b2e7c63",
    "outputs": [
      {
        "amount": 0,
        "match": true,
        "output_idx": 0,
        "output_pubkey": "765bfad81a43572164c29d34c5db84895a9995b34afd20c76f05bae672abff54"
      },
      {
        "amount": 0,
        "match": false,
        "output_idx": 1,
        "output_pubkey": "3f248e65c3a640a11508aa29e52420681a8ce81ec3a29f9c9ba53cf79dcd5e42"
      },
      {
        "amount": 0,
        "match": true,
        "output_idx": 2,
        "output_pubkey": "c07f3fc441b0284f4b15eafcbd1fd39becccae534abe51cd48e0e9ea87c5a31e"
      }
    ],
    "tx_hash": "5d7020f5c6e0bce1b74949d664b47da6e6a8022217756e280e83092ba1695308",
    "tx_prove": false,
    "viewkey": "3962197fb77a6d00a181d2a65ab7db32f90246bba10a2e75fce75ab37ff40c00"
  },
  "status": "success"
}
```

I sent this transaction myself, and the amount of outputs `0` and `2` should be 0.2 xmr and 0.4 xmr.  I own the Recipient Address, and I know the values for `address` and `viewkey` are right.

A Monero core dev suggested creating an issue here, and mentioned that:

> After the fork there are some changes to the format of the transactions (for instance saving 56 bytes per output) and the explorer may simply fail to deserialize/decode the new format.

**Comment by moneroexamples** [comment]
I can also see some issue on my node with decoding outputs now when using your tx data: http://139.162.60.17:8082/myoutputs/5d7020f5c6e0bce1b74949d664b47da6e6a8022217756e280e83092ba1695308/73LByqK36eLKLgU5y6dLBTMtXsa9LXnPKU4Q9H38T33nLr8FYRU3xy2XtqzgBRTuNG1qcRGmo818iBvrSB9Hz883CFohNJj/3962197fb77a6d00a181d2a65ab7db32f90246bba10a2e75fce75ab37ff40c00

Give me some time, I will look into it.

**Comment by moneroexamples** [comment]
Should be fixed now (https://github.com/moneroexamples/onion-monero-blockchain-explorer/commit/c05dfcf34a0ca57efd831f04904059600a332cee).

The fix is in the `master` branch of the explorer.

Your tx on the  updated explorer: http://139.162.60.17:8082/myoutputs/5d7020f5c6e0bce1b74949d664b47da6e6a8022217756e280e83092ba1695308/73LByqK36eLKLgU5y6dLBTMtXsa9LXnPKU4Q9H38T33nLr8FYRU3xy2XtqzgBRTuNG1qcRGmo818iBvrSB9Hz883CFohNJj/3962197fb77a6d00a181d2a65ab7db32f90246bba10a2e75fce75ab37ff40c00

**Comment by lalvarezguillen** [comment]
Nice catch. Thanks a lot!

**Comment by moneroexamples** [comment]
No problem. Can check now. If something new, please feel free to let me know.

**Comment by lalvarezguillen** [comment]
I've built and tested your fix, it has solved the problem I reported.
I'll close this issue.
Thanks a lot @moneroexamples !!
