### ISSUE TITLE
Setting up ssl

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#17]
Do you know how to set up ssl for crow? I can't find any documentation. I will be using lets encrypt, of course.

**Comment by moneroexamples** [comment]
It has some ssl, but dont know how to enale it, nor if it works. But I will check this and test how to setup certificate.  

Also my next project (not using crow) will suport ssl. There is already basic info in the readme about seting up your own certificates, but the the project is not yet finish, so readme is very lacking.

**Comment by moneroexamples** [comment]
Just added the suport and info how to use it. Its in the readme. Hopefuly it will help.

**Comment by moneroexamples** [comment]
Does ssl work as intented? If yes, maybe we can close this issue?

**Comment by Gingeropolous** [comment]
I haven't had a chance to recompile... we can assume it works, and if it doesn't I'll make another issue.

**Comment by moneroexamples** [comment]
Ok. If something, please let me know.
