### ISSUE TITLE
Error: invalid rct amount

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#177]
This address and viewkey can be used as an example:

```
44AFFq5kSiGBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVGQBEP3A

f359631075708155cc3d92a32b75a7d02a5dcf27756707b47a2b31b21c389501

```

Works on https://community.xmr.to , but not xmrchain.net

xmrchain.net is on monero master and explorer dev master

**Comment by moneroexamples** [comment]
Any specific tx that has the issue?

**Comment by Gingeropolous** [comment]
01d8e6934a224d02eee46a8e5483c3cb1c0b2eedd99a9d61915d10bf970d1fff

**Comment by moneroexamples** [comment]
I see now that it does not work with javascript-powered decoding of outputs. For the time being you could switch back to previous way, i.e., non-js version. I consider js functionality already deprecated for decoding outputs, etc. 

In future version of the explorer, js functionality will be removed, and replaced with https://github.com/moneroexamples/xmregcore for decoding txs and supporting sub-addresses.

**Comment by Gingeropolous** [comment]
OK, well when i switch back to the other version, it always produces links to localhost.

http://localhost:8888/myoutputs/01d8e6934a224d02eee46a8e5483c3cb1c0b2eedd99a9d61915d10bf970d1fff/44AFFq5kSiGBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVGQBEP3A/f359631075708155cc3d92a32b75a7d02a5dcf27756707b47a2b31b21c389501

you can goto the page for the same tx stuff as above to get the link

https://www.xmrchain.net/myoutputs

**Comment by moneroexamples** [comment]
I modified the link url as follows:

https://github.com/moneroexamples/onion-monero-blockchain-explorer/blob/7fca3a5df71cb3e4c6691f519cc16c94d0126e83/src/templates/my_outputs.html#L81

So now you can hardcode the xmrchain domain in the themplate file:

Instead of 
```
 <a href="{{domain_url}}{{shortcut_url}}" target="_blank">link to this page</a>
```
you can write
```
 <a href="https://xmrchain.org{{shortcut_url}}" target="_blank">link to this page</a>
```

**Comment by Gingeropolous** [comment]
i build dev. Thanks.

**Comment by moneroexamples** [comment]
No problem. Hope it works now.
