### ISSUE TITLE
Aborted (core dumped) [possible memleak?]

### ISSUE THREAD

**Issue by camthegeek** [moneroexamples/onion-monero-blockchain-explorer#179]
Branch being used is `aeon` 

Uptime on block explorer was a little over 24 hours.
FYI: application was renamed to `winblocks123` (not that it matters but other logs will show this a lot).

First log file: http://paste.debian.net/hidden/d15ab93f/
I noticed the error stated `double free or corruption (fasttop)`. Memory leak related?

Second log with the backtrace: http://paste.debian.net/hidden/17f51803/

So far, it has been a one-time error. 

Let me know if any of the above is useful, or useless.

Thanks

**Comment by moneroexamples** [comment]
I don't really maintain this branch. Maybe @stoffu will be able to help?

**Comment by stoffu** [comment]
Never seen this before and can't seem to reproduce it myself. Hard to debug it with the provided info only.

**Comment by camthegeek** [comment]
Since provided log information is not of any use and as this was a one-time incident, I'm going to close the issue.  I am hoping that it does not occur again. Thanks!
