### ISSUE TITLE
can't compile on ubuntu 16

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#18]
monero head compiles fine.

dunno why this is borkin

[ 94%] Building CXX object CMakeFiles/xmrblocks.dir/main.cpp.o
In file included from /home/user/onion-monero-blockchain-explorer/main.cpp:7:0:
/home/user/onion-monero-blockchain-explorer/src/page.h: In member function ‘std::__cxx11::string xmreg::page::show_checkcheckrawoutput(std::__cxx11::string, std::__cxx11::string)’:
/home/user/onion-monero-blockchain-explorer/src/page.h:2696:13: error: ‘portable_binary_iarchive’ is not a member of ‘boost::archive’
             boost::archive::portable_binary_iarchive ar(iss);
             ^
/home/user/onion-monero-blockchain-explorer/src/page.h:2698:13: error: ‘ar’ was not declared in this scope
             ar >> outputs;
             ^
CMakeFiles/xmrblocks.dir/build.make:62: recipe for target 'CMakeFiles/xmrblocks.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/xmrblocks.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/xmrblocks.dir/all' failed
make[1]: *** [CMakeFiles/xmrblocks.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
user@z170e4:~/onion-monero-blockchain-explorer$

**Comment by moneroexamples** [comment]
Need latest monero. Since 0.10.1 got release, there were changes to boost archiving done in monero to fix some issues with archives. Blockchain explorer was adapted to these changes, thus you need to have latest development version of monero.

**Comment by Gingeropolous** [comment]
Still can't compile. On latest head of Monero.

[ 94%] Building CXX object CMakeFiles/xmrblocks.dir/main.cpp.o
In file included from /usr/include/boost/serialization/serialization.hpp:44:0,
                 from /opt/monero-dev/headers/src/cryptonote_core/blockchain.h:32,
                 from /home/monerosupport/onion-monero-blockchain-explorer/src/monero_headers.h:25,
                 from /home/monerosupport/onion-monero-blockchain-explorer/src/MicroCore.h:10,
                 from /home/monerosupport/onion-monero-blockchain-explorer/main.cpp:6:
/usr/include/boost/serialization/access.hpp: In instantiation of ‘static void boost::serialization::access::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::portable_binary_iarchive; T = tools::wallet2::unsigned_tx_set]’:
/usr/include/boost/serialization/serialization.hpp:69:22:   required from ‘void boost::serialization::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::portable_binary_iarchive; T = tools::wallet2::unsigned_tx_set]’
/usr/include/boost/serialization/serialization.hpp:128:18:   required from ‘void boost::serialization::serialize_adl(Archive&, T&, unsigned int) [with Archive = boost::archive::portable_binary_iarchive; T = tools::wallet2::unsigned_tx_set]’
/usr/include/boost/archive/detail/iserializer.hpp:184:40:   required from ‘void boost::archive::detail::iserializer<Archive, T>::load_object_data(boost::archive::detail::basic_iarchive&, void*, unsigned int) const [with Archive = boost::archive::portable_binary_iarchive; T = tools::wallet2::unsigned_tx_set]’
/usr/include/boost/archive/detail/iserializer.hpp:116:1:   required from ‘class boost::archive::detail::iserializer<boost::archive::portable_binary_iarchive, tools::wallet2::unsigned_tx_set>’
/usr/include/boost/archive/detail/iserializer.hpp:410:13:   required from ‘static void boost::archive::detail::load_non_pointer_type<Archive>::load_standard::invoke(Archive&, const T&) [with T = tools::wallet2::unsigned_tx_set; Archive = boost::archive::portable_binary_iarchive]’
/usr/include/boost/archive/detail/iserializer.hpp:462:22:   required from ‘static void boost::archive::detail::load_non_pointer_type<Archive>::invoke(Archive&, T&) [with T = tools::wallet2::unsigned_tx_set; Archive = boost::archive::portable_binary_iarchive]’
/usr/include/boost/archive/detail/iserializer.hpp:618:18:   required from ‘void boost::archive::load(Archive&, T&) [with Archive = boost::archive::portable_binary_iarchive; T = tools::wallet2::unsigned_tx_set]’
/usr/include/boost/archive/detail/common_iarchive.hpp:66:22:   required from ‘void boost::archive::detail::common_iarchive<Archive>::load_override(T&, int) [with T = tools::wallet2::unsigned_tx_set; Archive = boost::archive::portable_binary_iarchive]’
/opt/monero-dev/headers/external/boost/archive/portable_binary_iarchive.hpp:168:9:   required from ‘void boost::archive::portable_binary_iarchive::load_override(T&, int) [with T = tools::wallet2::unsigned_tx_set]’
/usr/include/boost/archive/detail/interface_iarchive.hpp:60:9:   required from ‘Archive& boost::archive::detail::interface_iarchive<Archive>::operator>>(T&) [with T = tools::wallet2::unsigned_tx_set; Archive = boost::archive::portable_binary_iarchive]’
/home/monerosupport/onion-monero-blockchain-explorer/src/page.h:1610:23:   required from here
/usr/include/boost/serialization/access.hpp:118:9: error: ‘struct tools::wallet2::unsigned_tx_set’ has no member named ‘serialize’
         t.serialize(ar, file_version);
         ^
/usr/include/boost/serialization/access.hpp: In instantiation of ‘static void boost::serialization::access::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::portable_binary_iarchive; T = tools::wallet2::signed_tx_set]’:
/usr/include/boost/serialization/serialization.hpp:69:22:   required from ‘void boost::serialization::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::portable_binary_iarchive; T = tools::wallet2::signed_tx_set]’
/usr/include/boost/serialization/serialization.hpp:128:18:   required from ‘void boost::serialization::serialize_adl(Archive&, T&, unsigned int) [with Archive = boost::archive::portable_binary_iarchive; T = tools::wallet2::signed_tx_set]’
/usr/include/boost/archive/detail/iserializer.hpp:184:40:   required from ‘void boost::archive::detail::iserializer<Archive, T>::load_object_data(boost::archive::detail::basic_iarchive&, void*, unsigned int) const [with Archive = boost::archive::portable_binary_iarchive; T = tools::wallet2::signed_tx_set]’
/usr/include/boost/archive/detail/iserializer.hpp:116:1:   required from ‘class boost::archive::detail::iserializer<boost::archive::portable_binary_iarchive, tools::wallet2::signed_tx_set>’
/usr/include/boost/archive/detail/iserializer.hpp:410:13:   required from ‘static void boost::archive::detail::load_non_pointer_type<Archive>::load_standard::invoke(Archive&, const T&) [with T = tools::wallet2::signed_tx_set; Archive = boost::archive::portable_binary_iarchive]’
/usr/include/boost/archive/detail/iserializer.hpp:462:22:   required from ‘static void boost::archive::detail::load_non_pointer_type<Archive>::invoke(Archive&, T&) [with T = tools::wallet2::signed_tx_set; Archive = boost::archive::portable_binary_iarchive]’
/usr/include/boost/archive/detail/iserializer.hpp:618:18:   required from ‘void boost::archive::load(Archive&, T&) [with Archive = boost::archive::portable_binary_iarchive; T = tools::wallet2::signed_tx_set]’
/usr/include/boost/archive/detail/common_iarchive.hpp:66:22:   required from ‘void boost::archive::detail::common_iarchive<Archive>::load_override(T&, int) [with T = tools::wallet2::signed_tx_set; Archive = boost::archive::portable_binary_iarchive]’
/opt/monero-dev/headers/external/boost/archive/portable_binary_iarchive.hpp:168:9:   required from ‘void boost::archive::portable_binary_iarchive::load_override(T&, int) [with T = tools::wallet2::signed_tx_set]’
/usr/include/boost/archive/detail/interface_iarchive.hpp:60:9:   required from ‘Archive& boost::archive::detail::interface_iarchive<Archive>::operator>>(T&) [with T = tools::wallet2::signed_tx_set; Archive = boost::archive::portable_binary_iarchive]’
/home/monerosupport/onion-monero-blockchain-explorer/src/page.h:1879:23:   required from here
/usr/include/boost/serialization/access.hpp:118:9: error: ‘struct tools::wallet2::signed_tx_set’ has no member named ‘serialize’
CMakeFiles/xmrblocks.dir/build.make:62: recipe for target 'CMakeFiles/xmrblocks.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/xmrblocks.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/xmrblocks.dir/all' failed
make[1]: *** [CMakeFiles/xmrblocks.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by moneroexamples** [comment]
Ok. Let me check on 16.04, and will get back to you. Thanks.

**Comment by moneroexamples** [comment]
Just tried on fresh 16.04 desktop (you use server?) and it worked for me. Usually when I compile new monero, or any other project, I just download fresh copy of the source and compile everything from scratch. 

I would suggest removing entire monero source code folder, and get new one from today. 

Once Monero is compiled from scratch, delete old `/opt/monero-dev` folder and setup headers and files from scratch as indicated here:
 - https://github.com/moneroexamples/compile-monero-09-on-ubuntu-16-04

Note: the `rsync` command has changed a bit recently to account for new serialisation file headers in monero. Your error seem to be due to problems with serialization files: `portable_binary_iarchive.hpp` from monero. Maybe they didnt get updated properly?

Then get fresh copy of source of the explorer and trying compiling it. 

Just to complete, I tested the compilation on ubuntu in vm of these details: http://i.imgur.com/d3STqFg.png

If there will be still problems, I can make compilation of parts of the explorer that relay on monero's serialization files optional. This will eliminate tx pusher from the explorer, but should make it compile. 

Please let me know how it will go and I will try to help.

**Comment by Snipa22** [comment]
Hello,

This was compiled from a clean copy of 16.04.1 LTS server, monerod had no issues at all.  The entire project was built from Master, 2 days before the most recent merges occoured.  We'll give the copy another shot at this point, but there's no real reason I can see that it should matter.

**Comment by moneroexamples** [comment]
@Snipa22 

Thank you for the info. If the problem persists I will make the compiling tx pusher optional, as this uses the monero's boost archiving library. 

btw. I relaunch the onion version of the onion explorer, if anyone interested to see the latest version or test the tx pusher or other things. The onion address is: http://3ccmeg4dunrl7h3i.onion/

**Comment by kenshi84** [comment]
@moneroexamples Sweet, now the explorer accepts all kinds of binary files created on my Mac machine:) Thank you so much!

**Comment by moneroexamples** [comment]
@kenshi84

Happy its working. If something, please dont hesitate to let me know.

**Comment by Gingeropolous** [comment]
So I ended up compiling on Ubuntu desktop and then pushing the binaries to Snipa's ubuntu server. Don't think this really fixes the issue, but it seems like I should close it anyway.
