### ISSUE TITLE
How to stop daemon?

### ISSUE THREAD

**Issue by jarole** [moneroexamples/onion-monero-blockchain-explorer#182]
**Question**
How can I stop xmrblocks? I always have to find and kill the process. 

**Feature Request** :)
Would it be possible to add a parameter for that like `stop` or `exit` ?

Thanks

**Comment by moneroexamples** [comment]
`Control+C` should do it. For now it will just kill it. For now `Control+C` is not intercepted by the xmrblocks for graceful shutdown. Its one of those features that is on `to-do-list` but never have time to actually implement it, as always there some more pressing things to do.

**Comment by jarole** [comment]
It's OK, I am just wondering if  I miss something. This feature is not so important and if you have it in `to-do-list` I am closing  this issue.

I use 
`killall xmrblocks` 
because daemon is running on the background.

Thank you!
