### ISSUE TITLE
Got further, but still can't compile

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#2]
[100%] Building CXX object CMakeFiles/xmrblocks.dir/main.cpp.o
Linking CXX executable xmrblocks
/usr/bin/ld: _ZN5boost4asio6detail15keyword_tss_ptrINS1_10call_stackINS1_15task_io_serviceENS1_27task_io_service_thread_infoEE7contextEE6value_E: TLS definition in CMakeFiles/xmrblocks.dir/main.cpp.o section .tbss._ZN5boost4asio6detail15keyword_tss_ptrINS1_10call_stackINS1_15task_io_serviceENS1_27task_io_service_thread_infoEE7contextEE6value_E[_ZN5boost4asio6detail15keyword_tss_ptrINS1_10call_stackINS1_15task_io_serviceENS1_27task_io_service_thread_infoEE7contextEE6value_E] mismatches non-TLS definition in blockchain.cpp.o (symbol from plugin) section .gnu.linkonce.t._ZN5boost4asio6detail15keyword_tss_ptrINS1_10call_stackINS1_15task_io_serviceENS1_27task_io_service_thread_infoEE7contextEE6value_E
/opt/bitmonero-dev/libs/libcryptonote_core.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [xmrblocks] Error 1
make[1]: *** [CMakeFiles/xmrblocks.dir/all] Error 2
make: *** [all] Error 2
bob@monkey-desktop:~/onion-monero-blockchain-explorer$

Any suggestions?

**Comment by moneroexamples** [comment]
What os?

**Comment by Gingeropolous** [comment]
bob@monkey-desktop:~/onion-monero-blockchain-explorer$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

**Comment by moneroexamples** [comment]
I see. 14.04. Havent tested it on 14.04. The oldest ubuntu I used was 15.10. But I will check it on 14.04, but cant do now. You will have to wait a week or so before I do that. Sorry. Have no access to my development computer wright now.

**Comment by Gingeropolous** [comment]
gotcha. I will consider moving to the new LTS ubuntu perhaps for my ISO i develop

**Comment by Gingeropolous** [comment]
I seem to have everything compiled now. I used gcc 5.3 for the compile on ubuntu 16.

**Comment by moneroexamples** [comment]
Cool. Let me know how it works and if it works at all for someone then me:-)
