### ISSUE TITLE
Add support for --daemon-login user:pass

### ISSUE THREAD

**Issue by moneroexamples** [moneroexamples/onion-monero-blockchain-explorer#200]
When monero daemon uses `--rpc-login=user:pass`, blockchain explorer won't be able to connect to it to get mempool or other network data.

`--daemon-login user:pass` should be added the explorer to solve this.

**Comment by shermand100** [comment]
Built using the xmrblocks dev branch and confirm working using the following:

Raspbian Buster OS

Monerod started with:

`cd /home/$USER/monero/`
`./monero-active/monerod --rpc-bind-ip=192.168.1.105 --rpc-bind-port=18083 --rpc-login=user:pass --confirm-external-bind --rpc-ssl disabled`

xmrblocks started with:

`cd /home/$USER/onion-monero-blockchain-explorer/build/`
`./xmrblocks --port 8081 --enable-pusher --enable-emission-monitor --deamon-url=http://192.168.1.105:18083 --daemon-login user:pass`

Thanks for adding this.

**Comment by moneroexamples** [comment]
Glad its working.

**Comment by Tikhon88** [comment]
#200

**Comment by moneroexamples** [comment]
@Tikhon88 

?

**Comment by moneroexamples** [comment]
I think this issue is solved. Closing.
