### ISSUE TITLE
Tx_Pool Age is wrong

### ISSUE THREAD

**Issue by ilie1988** [moneroexamples/onion-monero-blockchain-explorer#202]
Hello,

there is a commit that breaks the tx pool age, it anonymes the taxes from tx pool

https://github.com/monero-project/monero/commit/5d7ae2d2791c0244a221872a7ac62627abb81896#diff-e0629185a2adeca3fbc0f3ce27a79d65

![image](https://user-images.githubusercontent.com/56231050/71882518-ea77c680-3134-11ea-9b04-b0a11d4bfda2.png)

Best Regards,
ILIE

**Comment by moneroexamples** [comment]
Thanks. I can replicate the issue.

**Comment by moneroexamples** [comment]
You can check now, `master` branch.

**Comment by ilie1988** [comment]
I can confirm that it works :) Thanks
