### ISSUE TITLE
Return related transaction to public keys in API

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [moneroexamples/onion-monero-blockchain-explorer#213]
The browser currently allows you to work backwards from a decoy output to the transaction that it is created in. This is not possible when using the API. The API presents the "block_no" and "public_key." While I can query the block for the list of transactions and build a local database to see which transaction matches the public key, I would rather the API return the transaction that the public_key is associated with like in the web version. This would save me multiple API requests when trying to work backwards from decoys.

**Comment by moneroexamples** [comment]
Thanks for the info. I will check that.

**Comment by rbrunner7** [comment]
I stumbled over the same issue today. While the public keys that the API now returns in the mixin data are very hard to process further, transaction hashes would be much more useful and of course straightforward to process.

**Comment by moneroexamples** [comment]
You mean the following APi endpoint?

[api/outputs?txhash=<tx_hash>&address=&viewkey=&txprove=<0|1>](https://github.com/moneroexamples/onion-monero-blockchain-explorer#apioutputstxhashtx_hashaddressviewkeytxprove01)

**Comment by rbrunner7** [comment]
No, like most probably @SamsungGalaxyPlayer as well I refer to `api/transaction/<tx_hash>`. When it lists the "mixins" of the transaction, it gives "public_key". This is quite unwieldy to query further as far as I could see.

Imagine I want to use the API to produce a nice list of the ring members of a transaction, showing which transactions the decoy outputs are from, like the explorer does in HTML.

As a workaround I intend to use that, grab the HTML the explorer produces and locate the links to the ring members to get at the info, as an alternative to using the API.

**Comment by moneroexamples** [comment]
Added to branch https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/api_tx

The branch builds with monero's  `release-v0.17`. If you have time, you can check. 

@SamsungGalaxyPlayer  Sorry it took so long.

**Comment by rbrunner7** [comment]
Tested, works. Thanks!

**Comment by moneroexamples** [comment]
r@rbrunner7 Thanks. Soon will merge to master branch.

**Comment by moneroexamples** [comment]
Marge. Closing. 
https://github.com/moneroexamples/onion-monero-blockchain-explorer/pull/229
