### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by blockchainOSINT** [moneroexamples/onion-monero-blockchain-explorer#219]
I'm using Visual Studio Build Tools 16.7.5 on Windows 10 Pro to compile **main.cpp**  however I keep running into this error

```
C:\Users\...\Source\Repos\onion-monero-blockchain-explorer>cl /EHsc main.cpp

src/page.h(10): fatal error C1083: Cannot open include file: 'mstch/mstch.hpp': No such file or directory
```
Please excuse my ignorance on not knowing how to compile a C++ file. I looked for resources to explain the problem but struck out.

**Comment by moneroexamples** [comment]
Sadly I'm not naively developing it for windows. A current support was for windows was provided through community members.

**Comment by blockchainOSINT** [comment]
Good call, I just compiled it on an Ubuntu VM and it was much easier. Appreciate the reply.
