### ISSUE TITLE
JSON API Error

### ISSUE THREAD

**Issue by blockchainOSINT** [moneroexamples/onion-monero-blockchain-explorer#220]
I'm using the Python requests module to make get calls to the json API.  For the api/blocks/{block_height} call, some blocks come back with the proper content and some blocks do not.

```
>>> url = "http://127.0.0.1:8081/api/block/795002"
>>> r = requests.get(url)
>>> r.content
b'{"data":{"block_height":795002,"current_height":2200666,"hash":"38ba39e9e441b6d52ea81222b64ac0a53cd6b23dbdab95e20022e6c6d7cdb7b5","size":210,"timestamp":1445632181,"timestamp_utc":"2015-10-23 20:29:41","txs":[{"coinbase":true,"extra":"01d82cc232c6c05e1b6cfa61bccaa00f299db8f63bb411a292abd5a158ea1d23fb020800000006cda42141","mixin":0,"payment_id":"","payment_id8":"","rct_type":0,"tx_fee":0,"tx_hash":"4d8cbdaab2e83ad46f0d9ff6a33be1e527794c682d2fa55dd729884d44e7521c","tx_size":210,"tx_version":1,"xmr_inputs":0,"xmr_outputs":8263679146121}]},"status":"success"}'

>>> url = "http://127.0.0.1:8081/api/block/795001"
>>> r = requests.get(url)
>>> r.content
b'{"data":null,"message":"Cant get transactions in block: 795001","status":"error"}'
```

Wondering why this happens from some blocks but not others, and if there's a fix?

**Comment by moneroexamples** [comment]
This is for mainnet?

**Comment by blockchainOSINT** [comment]
Yes, mainnet. I'm resyncing the blockchain to see if that will make a difference. Any idea why that may be happening? More blocks come back with {"data": null} than with the right content.

**Comment by blockchainOSINT** [comment]
Resyncing the blockchain worked.

Thank you for this amazing tool. Get requests are 100x faster using xmrblocks API vs using xmrchain.net or blox.minexmr.com.

**Comment by moneroexamples** [comment]
No problem. Glad it worked out.
