### ISSUE TITLE
"Link to this page" in transaction prove gives 404

### ISSUE THREAD

**Issue by dginovker** [moneroexamples/onion-monero-blockchain-explorer#223]
When using the transaction proof (which is great, btw), you have to input all the fields yourself, but can't send a URL for the recipient to see as well since the URL stays the same. Can you make the tx hash and address be in the URL bar so we can copy-paste it like regular txids?

**Comment by dginovker** [comment]
Edit: There seems to be a "link to this page" but it's broken: https://i.imgur.com/M8TypKw.png

**Comment by moneroexamples** [comment]
Thanks. I will look into it.

**Comment by moneroexamples** [comment]
Not sure what do you mean. In my tests the link works as expected. Can you clarify or provide some more informative example/screenshot. 

Also, where did you get the screenshot from? Its not from https://xmrchain.org/ ?

**Comment by moneroexamples** [comment]
Closing due to lack up updates.
