### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by berghemhack** [moneroexamples/onion-monero-blockchain-explorer#225]
...

**Comment by berghemhack** [comment]
/home/user/onion-monero-blockchain-explorer/src/page.h: In member function ‘xmreg::json xmreg::page::show_ringmemberstx_jsonhex(const string&)’:
/home/user/onion-monero-blockchain-explorer/src/page.h:1754:63: error: no matching function for call to ‘store_t_to_binary(cryptonote::block_complete_entry&, epee::byte_slice&)’
complete_block_data, complete_block_data_slice))
^
Ubuntu 20.04.1 LTS
gcc (Ubuntu 8.4.0-3ubuntu2) 8.4.0
g++ (Ubuntu 8.4.0-3ubuntu2) 8.4.0

I downgraded to the old page.h and now it is working.

**Comment by moneroexamples** [comment]
What version of monero are you compiling against?

**Comment by berghemhack** [comment]
release-v0.17 with USE_SINGLE_BUILDDIR=1 make

**Comment by tevador** [comment]
I confirm that the build fails using revision 1812527 (+ latest release-v0.17 Monero branch).

```
/home/user/onion-monero-blockchain-explorer/src/page.h: In member function ‘std::string xmreg::page::show_block_hex(size_t, bool)’:
/home/user/onion-monero-blockchain-explorer/src/page.h:1453:71: error: no matching function for call to ‘store_t_to_binary(cryptonote::block_complete_entry&, epee::byte_slice&)’
 1453 |                         complete_block_data, complete_block_data_slice))
      |                                                                       ^
In file included from /home/user/monero/contrib/epee/include/storages/http_abstract_invoke.h:32,
                 from /home/user/onion-monero-blockchain-explorer/src/monero_headers.h:22,
                 from /home/user/onion-monero-blockchain-explorer/src/page.h:12,
                 from /home/user/onion-monero-blockchain-explorer/main.cpp:4:
```

**Comment by moneroexamples** [comment]
Thanks. I will look into it.

**Comment by moneroexamples** [comment]
I reverted the PR that broke branch `release-v0.17`. You can have a re-try now.

**Comment by berghemhack** [comment]
Now everything is ok, well done!
