### ISSUE TITLE
triptych is coming!

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#227]
https://github.com/moneromooo-monero/bitmonero/commit/20873b6ade3d5418518dd67678b5831445bae130

and BP+

**Comment by moneroexamples** [comment]
Thanks. Note to myself, its in branch: https://github.com/moneromooo-monero/bitmonero/tree/crash

**Comment by Gingeropolous** [comment]
thank YOU dude. your work is amazing.

**Comment by moneroexamples** [comment]
Closing. I think triptych is not coming any time soon :-)

**Comment by Gingeropolous** [comment]
lol. indeed. sorry i got all excited about that.
