### ISSUE TITLE
Possible to Identify Atomic Swaps?

### ISSUE THREAD

**Issue by keatond** [moneroexamples/onion-monero-blockchain-explorer#233]
I have been trying to hunt down this question for awhile now. Would it be possible to enhance the current XMRChain explorer to be able to identify if a transaction was used in an Atomic Swap? I wasn't sure if there was a specific flag or identifier to know if the transaction was an Atomic Swap or not. It would be interesting to track to see the utilization of the feature.

**Comment by moneroexamples** [comment]
I don't know if atomic swaps leave any trace on the blackchain. Do you have any reference for such a "specific flag or identifier"?
