### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by de-biddo** [moneroexamples/onion-monero-blockchain-explorer#234]
When I compile it I get an error saying 

`/root/explore/src/page.h: In member function ‘std::string xmreg::page::show_block_hex(size_t, bool)’:
/root/explore/src/page.h:1452:69: error: no matching function for call to ‘store_t_to_binary(cryptonote::block_complete_entry&, std::string&)’
 1452 |                         complete_block_data, complete_block_data_str))
      |                                                                     ^
In file included from /root/monero/contrib/epee/include/storages/http_abstract_invoke.h:33,
                 from /root/explore/src/monero_headers.h:22,
                 from /root/explore/src/page.h:12,
                 from /root/explore/main.cpp:4:
/root/monero/contrib/epee/include/storages/portable_storage_template_helper.h:118:10: note: candidate: ‘template<class t_struct> bool epee::serialization::store_t_to_binary(t_struct&, epee::byte_slice&, size_t)’
  118 |     bool store_t_to_binary(t_struct& str_in, byte_slice& binary_buff, size_t initial_buffer_size = 8192)
      |          ^~~~~~~~~~~~~~~~~
/root/monero/contrib/epee/include/storages/portable_storage_template_helper.h:118:10: note:   template argument deduction/substitution failed:
In file included from /root/explore/main.cpp:4:
/root/explore/src/page.h:1452:46: note:   cannot convert ‘complete_block_data_str’ (type ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’}) to type ‘epee::byte_slice&’
 1452 |                         complete_block_data, complete_block_data_str))
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /root/monero/contrib/epee/include/storages/http_abstract_invoke.h:33,
                 from /root/explore/src/monero_headers.h:22,
                 from /root/explore/src/page.h:12,
                 from /root/explore/main.cpp:4:
/root/monero/contrib/epee/include/storages/portable_storage_template_helper.h:126:16: note: candidate: ‘template<class t_struct> epee::byte_slice epee::serialization::store_t_to_binary(t_struct&, size_t)’
  126 |     byte_slice store_t_to_binary(t_struct& str_in, size_t initial_buffer_size = 8192)
      |                ^~~~~~~~~~~~~~~~~
/root/monero/contrib/epee/include/storages/portable_storage_template_helper.h:126:16: note:   template argument deduction/substitution failed:
In file included from /root/explore/main.cpp:4:
/root/explore/src/page.h:1452:46: note:   cannot convert ‘complete_block_data_str’ (type ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’}) to type ‘size_t’ {aka ‘long unsigned int’}
 1452 |                         complete_block_data, complete_block_data_str))
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /root/monero/contrib/epee/include/storages/http_abstract_invoke.h:33,
                 from /root/explore/src/monero_headers.h:22,
                 from /root/explore/src/page.h:12,
                 from /root/explore/main.cpp:4:
/root/monero/contrib/epee/include/storages/portable_storage_template_helper.h:134:10: note: candidate: ‘template<class t_struct> bool epee::serialization::store_t_to_binary(t_struct&, epee::byte_stream&)’
  134 |     bool store_t_to_binary(t_struct& str_in, byte_stream& binary_buff)
      |          ^~~~~~~~~~~~~~~~~
/root/monero/contrib/epee/include/storages/portable_storage_template_helper.h:134:10: note:   template argument deduction/substitution failed:
In file included from /root/explore/main.cpp:4:
/root/explore/src/page.h:1452:46: note:   cannot convert ‘complete_block_data_str’ (type ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’}) to type ‘epee::byte_stream&’
 1452 |                         complete_block_data, complete_block_data_str))
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~
/root/explore/src/page.h: In member function ‘xmreg::json xmreg::page::show_ringmemberstx_jsonhex(const string&)’:
/root/explore/src/page.h:1749:61: error: no matching function for call to ‘store_t_to_binary(cryptonote::block_complete_entry&, std::string&)’
 1749 |                 complete_block_data, complete_block_data_str))
      |                                                             ^
In file included from /root/monero/contrib/epee/include/storages/http_abstract_invoke.h:33,
                 from /root/explore/src/monero_headers.h:22,
                 from /root/explore/src/page.h:12,
                 from /root/explore/main.cpp:4:
/root/monero/contrib/epee/include/storages/portable_storage_template_helper.h:118:10: note: candidate: ‘template<class t_struct> bool epee::serialization::store_t_to_binary(t_struct&, epee::byte_slice&, size_t)’
  118 |     bool store_t_to_binary(t_struct& str_in, byte_slice& binary_buff, size_t initial_buffer_size = 8192)
      |          ^~~~~~~~~~~~~~~~~
/root/monero/contrib/epee/include/storages/portable_storage_template_helper.h:118:10: note:   template argument deduction/substitution failed:
In file included from /root/explore/main.cpp:4:
/root/explore/src/page.h:1749:38: note:   cannot convert ‘complete_block_data_str’ (type ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’}) to type ‘epee::byte_slice&’
 1749 |                 complete_block_data, complete_block_data_str))
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /root/monero/contrib/epee/include/storages/http_abstract_invoke.h:33,
                 from /root/explore/src/monero_headers.h:22,
                 from /root/explore/src/page.h:12,
                 from /root/explore/main.cpp:4:
/root/monero/contrib/epee/include/storages/portable_storage_template_helper.h:126:16: note: candidate: ‘template<class t_struct> epee::byte_slice epee::serialization::store_t_to_binary(t_struct&, size_t)’
  126 |     byte_slice store_t_to_binary(t_struct& str_in, size_t initial_buffer_size = 8192)
      |                ^~~~~~~~~~~~~~~~~
/root/monero/contrib/epee/include/storages/portable_storage_template_helper.h:126:16: note:   template argument deduction/substitution failed:
In file included from /root/explore/main.cpp:4:
/root/explore/src/page.h:1749:38: note:   cannot convert ‘complete_block_data_str’ (type ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’}) to type ‘size_t’ {aka ‘long unsigned int’}
 1749 |                 complete_block_data, complete_block_data_str))
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /root/monero/contrib/epee/include/storages/http_abstract_invoke.h:33,
                 from /root/explore/src/monero_headers.h:22,
                 from /root/explore/src/page.h:12,
                 from /root/explore/main.cpp:4:
/root/monero/contrib/epee/include/storages/portable_storage_template_helper.h:134:10: note: candidate: ‘template<class t_struct> bool epee::serialization::store_t_to_binary(t_struct&, epee::byte_stream&)’
  134 |     bool store_t_to_binary(t_struct& str_in, byte_stream& binary_buff)
      |          ^~~~~~~~~~~~~~~~~
/root/monero/contrib/epee/include/storages/portable_storage_template_helper.h:134:10: note:   template argument deduction/substitution failed:
In file included from /root/explore/main.cpp:4:
/root/explore/src/page.h:1749:38: note:   cannot convert ‘complete_block_data_str’ (type ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’}) to type ‘epee::byte_stream&’
 1749 |                 complete_block_data, complete_block_data_str))
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/xmrblocks.dir/build.make:63: CMakeFiles/xmrblocks.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:178: CMakeFiles/xmrblocks.dir/all] Error 2`

I have compiled monero and then I tried to compile the block explorer then this happened.

**Comment by de-biddo** [comment]
i tried devel branch. wow.

**Comment by moneroexamples** [comment]
devel branch of the explorer follows master branch of monero.

**Comment by de-biddo** [comment]
> 
> 
> devel branch of the explorer follows master branch of monero.

and it happened to fix my problem so thats cool
