### ISSUE TITLE
Needs work on mobile view

### ISSUE THREAD

**Issue by abel30567** [moneroexamples/onion-monero-blockchain-explorer#237]
Tried to decode outputs on my iPhone but it was confusing with additional input field appearing 
![388E47BC-F850-42E2-A4DC-5B3A8762261C](https://user-images.githubusercontent.com/26675088/122656375-fccaa200-d127-11eb-8b15-99a1c0747bb9.png)

**Comment by moneroexamples** [comment]
Thanks. Can you provide any info on how the issue can be reproduced without actually using iphone?

Also, the relevant html is here https://github.com/moneroexamples/onion-monero-blockchain-explorer/blob/58b002cb98da15113ce549b0e8acb7ac54080b99/src/templates/partials/tx_details.html#L82 Maybe you have have any suggestions on how to improve the code, to make it behave correctly on iphone?

**Comment by lalanza808** [comment]
Most browsers have a Responsive Design Mode which can help surface these types of display issues. On Firefox it's under Tools > Browser Tools > Responsive Design Mode (CTRL + SHIFT + M)

**Comment by abel30567** [comment]
I tried to reproduce the issue on the web using chrome and safari with responsive design mode but I was not able to reproduce it using my computer or any of those browsers. I had to connect to my iPhone's safari to work on the fix via safari developer inspector
