### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by techandbeers** [moneroexamples/onion-monero-blockchain-explorer#240]
-Ubuntu 18.04
-Monero -b release-v0.17, followed this guide https://github.com/moneroexamples/monero-compilation/blob/master/README.md exactly.
-Master branch of the explorer.

Get the following error when compiling, right at the end.

`[100%] Linking CXX executable xmrblocks
/home/ubuntu/monero/build/release/src/device/libdevice.a(device_default.cpp.o): In function `hw::core::device_default::get_transaction_prefix_hash(cryptonote::transaction_prefix const&, crypto::hash&)':
device_default.cpp:(.text+0x457): undefined reference to `cryptonote::get_transaction_prefix_hash(cryptonote::transaction_prefix const&, crypto::hash&)'
/home/ubuntu/monero/build/release/src/cryptonote_core/libcryptonote_core.a(blockchain.cpp.o): In function `cryptonote::Blockchain::check_tx_inputs(cryptonote::transaction&, cryptonote::tx_verification_context&, unsigned long*) const':
blockchain.cpp:(.text+0x2001d): undefined reference to `cryptonote::get_transaction_prefix_hash(cryptonote::transaction_prefix const&)'
/home/ubuntu/monero/build/release/src/cryptonote_core/libcryptonote_core.a(blockchain.cpp.o): In function `cryptonote::Blockchain::prepare_handle_incoming_blocks(std::vector<cryptonote::block_complete_entry, std::allocator<cryptonote::block_complete_entry> > const&, std::vector<cryptonote::block, std::allocator<cryptonote::block> >&)':
blockchain.cpp:(.text+0x2b0ff): undefined reference to `cryptonote::get_transaction_prefix_hash(cryptonote::transaction_prefix const&, crypto::hash&)'
/home/ubuntu/monero/build/release/src/cryptonote_core/libcryptonote_core.a(cryptonote_tx_utils.cpp.o): In function `cryptonote::construct_tx_with_tx_key(cryptonote::account_keys const&, std::unordered_map<crypto::public_key, cryptonote::subaddress_index, std::hash<crypto::public_key>, std::equal_to<crypto::public_key>, std::allocator<std::pair<crypto::public_key const, cryptonote::subaddress_index> > > const&, std::vector<cryptonote::tx_source_entry, std::allocator<cryptonote::tx_source_entry> >&, std::vector<cryptonote::tx_destination_entry, std::allocator<cryptonote::tx_destination_entry> >&, boost::optional<cryptonote::account_public_address> const&, std::vector<unsigned char, std::allocator<unsigned char> > const&, cryptonote::transaction&, unsigned long, epee::mlocked<tools::scrubbed<crypto::ec_scalar> > const&, std::vector<epee::mlocked<tools::scrubbed<crypto::ec_scalar> >, std::allocator<epee::mlocked<tools::scrubbed<crypto::ec_scalar> > > > const&, bool, rct::RCTConfig const&, rct::multisig_out*, bool)':
cryptonote_tx_utils.cpp:(.text+0x97c1): undefined reference to `cryptonote::get_transaction_prefix_hash(cryptonote::transaction_prefix const&, crypto::hash&)'
/home/ubuntu/monero/build/release/src/cryptonote_basic/libcryptonote_basic.a(cryptonote_format_utils.cpp.o): In function `cryptonote::get_pruned_transaction_hash(cryptonote::transaction const&, crypto::hash const&)':
cryptonote_format_utils.cpp:(.text+0x47c0): undefined reference to `cryptonote::get_transaction_prefix_hash(cryptonote::transaction_prefix const&, crypto::hash&)'
/home/ubuntu/monero/build/release/src/cryptonote_basic/libcryptonote_basic.a(cryptonote_format_utils.cpp.o): In function `cryptonote::calculate_transaction_hash(cryptonote::transaction const&, crypto::hash&, unsigned long*)':
cryptonote_format_utils.cpp:(.text+0xa8b8): undefined reference to `cryptonote::get_transaction_prefix_hash(cryptonote::transaction_prefix const&, crypto::hash&)'
/home/ubuntu/monero/build/release/src/cryptonote_basic/libcryptonote_basic.a(cryptonote_format_utils.cpp.o): In function `cryptonote::parse_and_validate_tx_from_blob(boost::basic_string_ref<char, std::char_traits<char> > const&, cryptonote::transaction&, crypto::hash&, crypto::hash&)':
cryptonote_format_utils.cpp:(.text+0x12931): undefined reference to `cryptonote::get_transaction_prefix_hash(cryptonote::transaction_prefix const&, crypto::hash&)'
CMakeFiles/xmrblocks.dir/main.cpp.o: In function `xmreg::page::construct_tx_context[abi:cxx11](cryptonote::transaction, unsigned short)':
main.cpp:(.text._ZN5xmreg4page20construct_tx_contextB5cxx11EN10cryptonote11transactionEt[_ZN5xmreg4page20construct_tx_contextB5cxx11EN10cryptonote11transactionEt]+0x24d8): undefined reference to `cryptonote::get_transaction_prefix_hash(cryptonote::transaction_prefix const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/xmrblocks.dir/build.make:142: recipe for target 'xmrblocks' failed
make[2]: *** [xmrblocks] Error 1
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/xmrblocks.dir/all' failed
make[1]: *** [CMakeFiles/xmrblocks.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by moneroexamples** [comment]
Did you use `master` branch of the explorer or `devel`?

**Comment by techandbeers** [comment]
Master, although I tried devel as well with no luck.

**Comment by techandbeers** [comment]
Just tried Master branch of Monero with devel branch of explorer, same results. Super weird. I had this working on a local machine earlier but now it isn't in a VPS running the same version of Ubuntu and same exact install process.

**Comment by moneroexamples** [comment]
I'm checking this. Stack with some  monero compilation issues at the moment: https://github.com/monero-project/monero/issues/7843

**Comment by moneroexamples** [comment]
Can you please check again with master branch of the explorer. I pushed some [fixes](https://github.com/moneroexamples/onion-monero-blockchain-explorer/commit/0c8823074a6a639937a4f8d9e107894d992cae24) which hopefully address the issue. I tested it on Ubuntu 20.04.

**Comment by moneroexamples** [comment]
Closing due to being resolved in https://github.com/moneroexamples/onion-monero-blockchain-explorer/commit/0c8823074a6a639937a4f8d9e107894d992cae24
