### ISSUE TITLE
XMRwallet.com ...not syncing....or delivering funds. over a week.

### ISSUE THREAD

**Issue by Tooniecoin** [moneroexamples/onion-monero-blockchain-explorer#256]
not syncing....or delivering funds. over a week

**Comment by Tooniecoin** [comment]
https://minergate.com/blockchain/xmr/block/85c0b9c37d175c9f6b36602b2a5466ca75c7973eed9c1580e5db06ec86fe6ccd

**Comment by Tooniecoin** [comment]
Server Error

**Comment by moneroexamples** [comment]
I'm not the developer or support staff at XMRwallet.com.

**Comment by Tooniecoin** [comment]
Will today...Thanks
