### ISSUE TITLE
Your project has been added to a list of copyfree works.

### ISSUE THREAD

**Issue by apotheon** [moneroexamples/onion-monero-blockchain-explorer#260]
http://copyfree.org/resources/works#Onion%20Monero%20Blockchain%20Expolorer

Please let me know if there are any inaccuracies to be corrected or
improvements to be made in the listing.

**Comment by moneroexamples** [comment]
Thanks looks good. A change I would suggest is maybe changing tag `analytics` into `blockchain` or `blockchain explorer`.

**Comment by apotheon** [comment]
Thanks for the suggestions.  I added both, left analytics there, and added monero as well.  I'm not sure how I missed adding monero and blockchain tags the first time around.

Is there a specific reason to remove analytics?

**Comment by moneroexamples** [comment]
Analytics suggests some kind of analysis or statistics of data done, such as "tracking" txs. But its fine to leave it if you want. 

p.s.
Also missed "monero" tag.
