### ISSUE TITLE
Unable to decrypt transaction inputs with the API

### ISSUE THREAD

**Issue by ACK-J** [moneroexamples/onion-monero-blockchain-explorer#261]
Through the GUI I can decode the outputs of a transaction and then there is a drop down that shows the decoded inputs. How can I accomplish this through the API? The closest thing I have found in the documentation is:
```
# we use here official Monero project's donation address as an example
curl  -w "\n" -X GET "http://127.0.0.1:8081/api/outputs?txhash=17049bc5f2d9fbca1ce8dae443bbbbed2fc02f1ee003ffdd0571996905faa831&address=44AFFq5kSiGBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVGQBEP3A&viewkey=f359631075708155cc3d92a32b75a7d02a5dcf27756707b47a2b31b21c389501&txprove=0"
```

I want to be able to point to the correct ring in the ring signature.

**Comment by ACK-J** [comment]
I found where in the code base that the ring signature is referenced within the API 

https://github.com/moneroexamples/onion-monero-blockchain-explorer/blob/9a37839f37abef0b8b94ceeba41ab51a41f3fbd8/src/page.h#L1826-L1831

**Comment by moneroexamples** [comment]
Thanks, I will look into it. Also can you confirm which branch of monero and explorer do you use?

**Comment by ACK-J** [comment]
![image](https://user-images.githubusercontent.com/60232273/153738490-d0189406-e894-4d6d-9561-da81027c25d9.png)

**Comment by moneroexamples** [comment]
Without spend key its not possible to reliably decode key images to find "true" outputs used in an outgoing transaction. Thus its not available in the API as to not cause confusion of "strange" result that can be obtained.

**Comment by moneroexamples** [comment]
When this functionality was added to GUI, it was much easier to guess the true outputs, way before RingCT. API was added later, and there was little benefit of adding API for that as well at that point.

Without key images, its not possible to determine true outputs. But I developed other program (https://github.com/moneroexamples/transactions-export) which allows to check how your outputs were [used in RingCT](https://github.com/moneroexamples/transactions-export#searching-txs-which-use-our-outputs-as-ring-members-and-their-frequency). For example, to check which outputs of yours are most "popular".

**Comment by ACK-J** [comment]
Yea I've been using your xmr2csv and its a great tool, my issue is that it only exports other transactions including my output as a decoy. In my specific scenario I'm looking to export the same information as xmr2csv but for my own transactions. It would be cool if xmr2csv could export the following info for a users transactions, not decoys.
`Timestamp,Block_no,Tx_hash,Output_pub_key,Key_image,ring_no/ring_size`
Most importantly is the last field that details the position of the true spend in the ring signature.

In regards to your last comment, should I not be considering the GUI's decoded inputs to be accurate? I'm just confused if it not accurate how is it decoding which input in the ring signature was the true spend?

**Comment by moneroexamples** [comment]
You are making good point about GUI. Maybe its time to remove it or have it disabled by default, as it will be even less useful with the new HF when ring size will be increased to 16.

I will have a look at `xmr2csv` and check if adding `ring_no/ring_size` would be reasonably "easy" to add.

**Comment by moneroexamples** [comment]
@ACK-J 

Guessing outputs is now disabled by default in a `devel` branch of the explorer.

**Comment by moneroexamples** [comment]
`devel` branch usually gets merged to master when monero HFs happen, as `devel` branch of the explorer is kept to work with current `master` branch of monero. The `master` branch of monero sis basically its development branch for future releases.
