### ISSUE TITLE
Error building on Arch. easylogging++.h: no such file or directory

### ISSUE THREAD

**Issue by Ashaman-** [moneroexamples/onion-monero-blockchain-explorer#27]
Scanning dependencies of target myxrm
[  5%] Building CXX object src/CMakeFiles/myxrm.dir/MicroCore.cpp.o
In file included from /home/user/onion-monero-blockchain-explorer/src/MicroCore.h:10:0,
                 from /home/user/onion-monero-blockchain-explorer/src/MicroCore.cpp:5:
/home/user/onion-monero-blockchain-explorer/src/monero_headers.h:34:27: fatal error: easylogging++.h: No such file or directory
 #include "easylogging++.h"

**Comment by moneroexamples** [comment]
Did you use latest latest development version of monero, with its headers and library files?  In last two days, number of pull requests were made to monero, refactoring its logging system. The explorer was adjusted to these changes, and without latest monero development version, it wont work.

**Comment by Ashaman-** [comment]
Thanks, that did the trick. I was using headers and libs from the .10.1 release version.
