### ISSUE TITLE
Docker image stuck at start

### ISSUE THREAD

**Issue by vdo** [moneroexamples/onion-monero-blockchain-explorer#271]
I'm using the Dockerfile provided to run a container sharing the volume with `monerod`, and it seems to detect the blockchain just fine, but it stays stuck with just this output:

```
vagrant@bullseye:~$ sudo docker logs explorer
2022-06-01 11:41:17.494	W The blockchain is on a rotating drive: this will be very slow, use an SSD if possible
```

Which is also very weird because the container is not running on a rotating drive, but on a NVMe:
```
vagrant@bullseye:~$ sudo docker exec -t explorer lsblk
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda      8:0    0  20G  0 disk
`-sda1   8:1    0  20G  0 part /home/monero/.bitmonero
vagrant@bullseye:~$ sudo docker exec -t explorer ls /sys/dev/block/8:1/
alignment_offset  discard_alignment  inflight	power  size   stat	 trace
dev		  holders	     partition	ro     start  subsystem  uevent
vagrant@bullseye:~$ sudo docker logs monerod --tail 3
2022-06-01 11:42:52.877	I Synced 40948/2636176 (1%, 2595228 left)
2022-06-01 11:42:53.078	I Synced 41048/2636176 (1%, 2595128 left)
2022-06-01 11:42:53.324	I Synced 41148/2636176 (1%, 2595028 left)
vagrant@bullseye:~$ sudo docker logs explorer
2022-06-01 11:41:17.494	W The blockchain is on a rotating drive: this will be very slow, use an SSD if possible
```
I tried on different hardware, on my laptop, vagrant boxes, VPS servers and with different parameters with the same result.
I also tried to avoid `--enable-autorefresh-option --enable-emission-monitor --enable-pusher` options

**Comment by moneroexamples** [comment]
You mean this warning? "The blockchain is on a rotating drive: this will be very slow, use an SSD if possible"? 

Does it normally work without docker?

**Comment by moneroexamples** [comment]
No follow up from OP.

**Comment by moneroexamples** [comment]
No follow up from OP.
