### ISSUE TITLE
2022-07-22 14:05:57.590	E invalid hash format: 2504606

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#275]
see that in the logs when i run it

also, still have a memory leak

**Comment by moneroexamples** [comment]
Could you be able to provide more info when  "invalid hash format" shows up or how to reproduce it?
At the moment I don't know what can be causing memory leak.

**Comment by Gingeropolous** [comment]
it was showing up when I started xmrblocks.... but now it doesn't seem to be happening. I think I had a wonky config file, because at one point I was missing tx details on the explorer.
