### ISSUE TITLE
Request: `stagenet.xmrchain.net` JSON API

### ISSUE THREAD

**Issue by BrianHenryIE** [moneroexamples/onion-monero-blockchain-explorer#290]
Hi,

I've been working on a PHP SDK to accompany this project. To date, I've been testing with real moneroj! I'd assumed I'd be able to use `stagenet.xmrchain.net/api/...` instead, but it 404s. I think it might be a simple configuration option for you to change. But maybe it's intentionally disabled?

Please enable it if possible.

https://github.com/BrianHenryIE/bh-php-monero-explorer

**Comment by moneroexamples** [comment]
Hi. I'm not admin xmrchain. @Gingeropolous  does, thus maybe he will be able to help.

**Comment by Gingeropolous** [comment]
hrm, I have the enable api line active in the conf.

```
--enable-json-api 1 \
```

i don't know what else needs fiddling....

**Comment by moneroexamples** [comment]
Closing b/c no further updates from OP.
