### ISSUE TITLE
Links to the api are returning 404 Not Found

### ISSUE THREAD

**Issue by Olsm** [moneroexamples/onion-monero-blockchain-explorer#291]
The API links are all returning "404 Not Found"

https://xmrchain.net/api/networkinfo
https://xmrchain.net/api/mempool
https://xmrchain.net/api/block/2956450
https://xmrchain.net/api/transactions?page=1&limit=25

**Comment by moneroexamples** [comment]
Hi. I do not administer xmrchain, but maybe api support was disabled. Maybe @Gingeropolous could help?

**Comment by BrianHenryIE** [comment]
Those links are working again. This can be closed.

**Comment by Gingeropolous** [comment]
Please consider running your own nodes folks. There is no need to be dependent on another's blockchain or explorer API. 

you can run monerod and xmrchain in screen sessions if you don't want to fiddle with daemon managers
