### ISSUE TITLE
"Cant get per kb dynamic fee esimate" error in networkinfo endpoint

### ISSUE THREAD

**Issue by Olsm** [moneroexamples/onion-monero-blockchain-explorer#292]
Sometimes the API returns this error on the networkinfo endpoint, then it resolves itself later in the day.

The full response is:

`{"data":null,"message":"Cant get per kb dynamic fee esimate","status":"error"}`

Why is this happening and how can we fix it?

**Comment by moneroexamples** [comment]
You have to provide more info. How exactly do you call it? Do you self-host the explorer? If so, which version, what options do you use?

**Comment by IThinkUFailed** [comment]
Hi there - I'll post the specifics for Olav who directed me here.

explorer version (api): master-2023-03-28-d669720 (1.2) | monero version: 0.18.2.2-eac1b86bb

The only options enabled are -p 80 and --enable-json-api

Accessing /api/networkinfo generates the following response:
` {"data":null,"message":"Cant get per kb dynamic fee esimate","status":"error"}`

If I try several minutes later it will work. Looking at the VPS I have deployed it on I see nothing to indicate the server being overloaded or running out of storage. The VPS is also based on RAID10 SSD so it's pretty quick and not running on a spinning disk.

Hopefully, you may be able to point us in the right direction to debugging this, thanks!

**Comment by moneroexamples** [comment]
You can check now. The issue was that `get_dynamic_per_kb_fee_estimate` to monero was failing. This is monero api thing. But now I made it that `/api/networkinfo` doesn't fully fail if `get_dynamic_per_kb_fee_estimate` fails.

**Comment by IThinkUFailed** [comment]
> You can check now. The issue was that `get_dynamic_per_kb_fee_estimate` call to monero was failing. This is monero api thing. But now I made it that `/api/networkinfo` doesn't fully fail if `get_dynamic_per_kb_fee_estimate` fails.

Thank you! We'll give it a shot and report back any issues experienced.
