### ISSUE TITLE
Can't get tx in mempool

### ISSUE THREAD

**Issue by suhz** [moneroexamples/onion-monero-blockchain-explorer#3]
whenever I tried to view a tx that is in mempool. I will always get this error message
> Cant get tx: fe559b0872c1bd679a3bb1c9de4393fa6a6269e9bdc04f19de2ecac05dfb5e68

In console
> tx with hash fe559b0872c1bd679a3bb1c9de4393fa6a6269e9bdc04f19de2ecac05dfb5e68 not found in db
> Cant get tx in blockchain: <fe559b0872c1bd679a3bb1c9de4393fa6a6269e9bdc04f19de2ecac05dfb5e68>.
>  Check mempool now
> (2016-07-27 01:03:21) [INFO    ] Response: 0x7f7850005d00 /tx/fe559b0872c1bd679a3bb1c9de4393fa6a6269e9bdc04f19de2ecac05dfb5e68 200 0

Any idea?

**Comment by suhz** [comment]
Solved! I forgot to patch the daemon.

**Comment by moneroexamples** [comment]
Ok:-)
