### ISSUE TITLE
Wrong tx_hash above block 1220517

### ISSUE THREAD

**Issue by DaWe35** [moneroexamples/onion-monero-blockchain-explorer#303]
Hi,

I found a weird issue on my local explorer. Every time I reload `http://localhost:8081/block/1220517` or any block above, I get a different, seemingly random tx_hash for the non-coinbase transactions:

![image](https://github.com/moneroexamples/onion-monero-blockchain-explorer/assets/10603822/034452fd-cad1-46a4-a67f-beab4bd32e57)

What is broken?
- The tx_hashes are wrong and are constantly changing on page reload when opening block 1220517 or above (I think it is the height of the v2 tx hardfork)
- I get a similarly wrong th_hash from the API, but the hash changes less frequently (not on every reload).

What is working?
- The official https://xmrchain.org/block/1220517 webpage works well, so it is only present on my local explorer.
- My local monerod RPC returns the correct th_hashes: `curl http://127.0.0.1:18089/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_block","params":{"height":1220517}}' -H 'Content-Type: application/json'`

My build:
- I built the explorer myself from the docker-compose.yml on this branch: https://github.com/DaWe35/onion-monero-blockchain-explorer/tree/docker-compose-with-prebuilt-docker-image. The docker image is available on Docker Hub: dawe35/xmrblocks:latest
- I run a pruned monerod, since it was already recommended by you in the docker-compose.yml example.

Do you have any ideas what did I broke? I didn't change anything in the related code.
Thank you

**Comment by moneroexamples** [comment]
Is it only for this one block? Also I don't know what changes have been introduced in the fork of the explorer that you use (i.e. fork of  `DaWe35`). Can you try on the original version of the explorer?

**Comment by DaWe35** [comment]
Hi, 

Any block above 1220517 contains non-existing seemingly random tx_hashes, so not only this block.

The only difference is the docker-compose.yml: https://github.com/moneroexamples/onion-monero-blockchain-explorer/compare/master...DaWe35:onion-monero-blockchain-explorer:docker-compose-with-prebuilt-docker-image

**Comment by DaWe35** [comment]
I can confirm this issue is not present when the blockchain is fully stored, so I opened a PR and removed the flag related to pruning. It is not a full fix and as I can see, the explorer should work with pruned txes.

It's possible that we have a bug in `get_pruned_transaction_hash()` or somewhere else.
