### ISSUE TITLE
the emission counter seems to have restarted or something

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#313]
on xmrchain.net, its reporting

Monero emission (fees) is 1357.219 (102987.068) as of 3168179 block

**Comment by SChernykh** [comment]
Monero emission just passed 2^64 piconeros, starting from block 3165917. The code in `CurrentBlockchainStatus` needs to use 128-bit integers now.

**Comment by moneroexamples** [comment]
Haven't managed to fix that yet, as there are issues with monero compilation on newest gcc on Arch: https://github.com/monero-project/monero/issues/9359

**Comment by donttracemebruh** [comment]
Any update on this issue?

**Comment by moneroexamples** [comment]
Give me few days to check. RL was quite hectic in recent days.

**Comment by donttracemebruh** [comment]
Cool, thanks for the update. 

It seems as though a few notable services including coinmarketcap and coingecko were dependent on this emission counter, as the supply count for both of these websites has been stuck at 18,446,744 XMR for the past month and a half. As a result Monero's marketcap rank on these lists is also innacurate.

**Comment by moneroexamples** [comment]
I pushed a tentative fix into `emission` branch for testing: https://github.com/moneroexamples/onion-monero-blockchain-explorer/commit/1cde0df84f75ea624bab11c863f71b2ae8d87524

Not it shows (at the time of my testing): 

```
Monero emission (fees) is 18464815.243604807284 (103453.676548509515) as of 3196036 block 
```

![image](https://github.com/user-attachments/assets/893ae173-3250-4097-bd9d-4bfe0b79276a)

To test it, pull `emission` branch  of the explorer and compile against `master` branch of monero.

Delete pre-existing, if any, `~/.bitmonero/lmdb/emission_amount.txt` This is a default file where the explorer keeps track of the emission. Once the new explorer is started with `--enable-emission-monitor` flag, it should start calculating the emission using `uint128_t` data type. This process is time consuming - few hours to go through entire blockchain. 

To calculate emission in monero daemon for verification, use `print_coinbase_tx_sum 0 <last_block_number>`. Monero daemon will also take time to calculate the total emission.

**Comment by Gingeropolous** [comment]
the emission counter is back!
