### ISSUE TITLE
devel branch: breaking merges to monero master

### ISSUE THREAD

**Issue by plowsof** [moneroexamples/onion-monero-blockchain-explorer#317]
not sure exactly which commit broke it, definitely recent.

**Comment by moneroexamples** [comment]
Not sure what you mean? Any specific errors?

**Comment by plowsof** [comment]
of course i forgot to save the output, i can confirm later but it was this commit which breaks the devel builds https://github.com/monero-project/monero/commit/ed955bf751e304569cd4c04f558360154e19610e

**Comment by moneroexamples** [comment]
Ok, thanks. I will have a look.

**Comment by moneroexamples** [comment]
I see some errors:

```
Mrcin Wolski

Dte of birth 28 Sept 1981
TFN: 859 068 956
I see some errors:

```
rivilly_copyble’?
  102 |   sttic_ssert(std::is_trivilly_copyble_v<decltype(this_ref.vrible)>, "t_type must be  trivilly copyble type."); \
      |                      ^~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/contrib/epee/include/seriliztion/keyvlue_seriliztion.h:121:59: note: in expnsion of mcro ‘KV_SERILIZE_VL_POD_S_BLOB_N’
  121 | #define KV_SERILIZE_VL_POD_S_BLOB(vrilble)           KV_SERILIZE_VL_POD_S_BLOB_N(vrilble, #vrilble)
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/src/wllet/messge_trnsporter.h:68:5: note: in expnsion of mcro ‘KV_SERILIZE_VL_POD_S_BLOB’
   68 |     KV_SERILIZE_VL_POD_S_BLOB(iv)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/contrib/epee/include/seriliztion/keyvlue_seriliztion.h:102:46: error: expected primry-expression before ‘decltype’
  102 |   sttic_ssert(std::is_trivilly_copyble_v<decltype(this_ref.vrible)>, "t_type must be  trivilly copyble type."); \
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/contrib/epee/include/seriliztion/keyvlue_seriliztion.h:121:59: note: in expnsion of mcro ‘KV_SERILIZE_VL_POD_S_BLOB_N’
  121 | #define KV_SERILIZE_VL_POD_S_BLOB(vrilble)           KV_SERILIZE_VL_POD_S_BLOB_N(vrilble, #vrilble)
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/src/wllet/messge_trnsporter.h:68:5: note: in expnsion of mcro ‘KV_SERILIZE_VL_POD_S_BLOB’
   68 |     KV_SERILIZE_VL_POD_S_BLOB(iv)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/contrib/epee/include/seriliztion/keyvlue_seriliztion.h:102:46: error: expected ‘,’ before ‘decltype’
  102 |   sttic_ssert(std::is_trivilly_copyble_v<decltype(this_ref.vrible)>, "t_type must be  trivilly copyble type."); \
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/contrib/epee/include/seriliztion/keyvlue_seriliztion.h:121:59: note: in expnsion of mcro ‘KV_SERILIZE_VL_POD_S_BLOB_N’
  121 | #define KV_SERILIZE_VL_POD_S_BLOB(vrilble)           KV_SERILIZE_VL_POD_S_BLOB_N(vrilble, #vrilble)
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/src/wllet/messge_trnsporter.h:68:5: note: in expnsion of mcro ‘KV_SERILIZE_VL_POD_S_BLOB’
   68 |     KV_SERILIZE_VL_POD_S_BLOB(iv)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/contrib/epee/include/seriliztion/keyvlue_seriliztion.h:102:46: error: expected string-literl before ‘decltype’
  102 |   sttic_ssert(std::is_trivilly_copyble_v<decltype(this_ref.vrible)>, "t_type must be  trivilly copyble type."); \
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/contrib/epee/include/seriliztion/keyvlue_seriliztion.h:121:59: note: in expnsion of mcro ‘KV_SERILIZE_VL_POD_S_BLOB_N’
  121 | #define KV_SERILIZE_VL_POD_S_BLOB(vrilble)           KV_SERILIZE_VL_POD_S_BLOB_N(vrilble, #vrilble)
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by moneroexamples** [comment]
The errors
```
rivilly_copyble’?
  102 |   sttic_ssert(std::is_trivilly_copyble_v<decltype(this_ref.vrible)>, "t_type must be  trivilly copyble type."); \
      |                      ^~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/contrib/epee/include/seriliztion/keyvlue_seriliztion.h:121:59: note: in expnsion of mcro ‘KV_SERILIZE_VL_POD_S_BLOB_N’
  121 | #define KV_SERILIZE_VL_POD_S_BLOB(vrilble)           KV_SERILIZE_VL_POD_S_BLOB_N(vrilble, #vrilble)
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/src/wllet/messge_trnsporter.h:68:5: note: in expnsion of mcro ‘KV_SERILIZE_VL_POD_S_BLOB’
   68 |     KV_SERILIZE_VL_POD_S_BLOB(iv)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/contrib/epee/include/seriliztion/keyvlue_seriliztion.h:102:46: error: expected primry-expression before ‘decltype’
  102 |   sttic_ssert(std::is_trivilly_copyble_v<decltype(this_ref.vrible)>, "t_type must be  trivilly copyble type."); \
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/contrib/epee/include/seriliztion/keyvlue_seriliztion.h:121:59: note: in expnsion of mcro ‘KV_SERILIZE_VL_POD_S_BLOB_N’
  121 | #define KV_SERILIZE_VL_POD_S_BLOB(vrilble)           KV_SERILIZE_VL_POD_S_BLOB_N(vrilble, #vrilble)
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/src/wllet/messge_trnsporter.h:68:5: note: in expnsion of mcro ‘KV_SERILIZE_VL_POD_S_BLOB’
   68 |     KV_SERILIZE_VL_POD_S_BLOB(iv)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/contrib/epee/include/seriliztion/keyvlue_seriliztion.h:102:46: error: expected ‘,’ before ‘decltype’
  102 |   sttic_ssert(std::is_trivilly_copyble_v<decltype(this_ref.vrible)>, "t_type must be  trivilly copyble type."); \
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/contrib/epee/include/seriliztion/keyvlue_seriliztion.h:121:59: note: in expnsion of mcro ‘KV_SERILIZE_VL_POD_S_BLOB_N’
  121 | #define KV_SERILIZE_VL_POD_S_BLOB(vrilble)           KV_SERILIZE_VL_POD_S_BLOB_N(vrilble, #vrilble)
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/src/wllet/messge_trnsporter.h:68:5: note: in expnsion of mcro ‘KV_SERILIZE_VL_POD_S_BLOB’
   68 |     KV_SERILIZE_VL_POD_S_BLOB(iv)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/contrib/epee/include/seriliztion/keyvlue_seriliztion.h:102:46: error: expected string-literl before ‘decltype’
  102 |   sttic_ssert(std::is_trivilly_copyble_v<decltype(this_ref.vrible)>, "t_type must be  trivilly copyble type."); \
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/a/monero/contrib/epee/include/seriliztion/keyvlue_seriliztion.h:121:59: note: in expnsion of mcro ‘KV_SERILIZE_VL_POD_S_BLOB_N’
  121 | #define KV_SERILIZE_VL_POD_S_BLOB(vrilble)           KV_SERILIZE_VL_POD_S_BLOB_N(vrilble, #vrilble)
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by moneroexamples** [comment]
This happens because monero switched to C++17: https://github.com/monero-project/monero/blob/master/CMakeLists.txt#L102 and the explorer is still on C++14.

**Comment by plowsof** [comment]
Do you have an estimate for how much work/hours it would take you to upgrade to c++17? Also do you have items on a todo list/ideas in the pipeline for this project or maintenance tasks?

**Comment by moneroexamples** [comment]
I started, but haven't finished. I try to do it this week.

**Comment by plowsof** [comment]
Thank you, by chance do you have donation addresses displayed anywhere?

**Comment by moneroexamples** [comment]
I pushed a fix to `devel` branch. If you have time, check if it compiles now. 

Thx, you can use: 41vEA7Ye8Bpeda6g59v5t46koWrVn2PNgEKgzquJjmiKCFTsh9gajr8J3pad49rqu581TAtFGCH9CYTCkYrCpuWUG9GkgeB

**Comment by plowsof** [comment]
thank you, i shall confirm now. is there a way to contact you directly (email/irc/matrix) i have messaged your reddit account from my knowledgemurky?? acc a while ago but the history is gone and i can't remember your username exactly. plowsof AT protonmail dot com if you dont want to share publicly

**Comment by plowsof** [comment]
devel now builds !

**Comment by f0o** [comment]
when will this be merged into master? current monero release v0.18.3.4 uses c++17 breaking the explorer's compilation

**Comment by moneroexamples** [comment]
@f0o 

Its been already merged in `devel` branch. The problem is with `master` branch of the explorer?

**Comment by f0o** [comment]
Yeah master with the latest monero release is the issue; However devel and monero's master works fine

**Comment by moneroexamples** [comment]
@f0o 

Monero v0.18.3.4 does not compile it self. I made issue for that 
https://github.com/monero-project/monero/issues/9619#issuecomment-2546230130
