### ISSUE TITLE
Xmrchain.net API no longer work

### ISSUE THREAD

**Issue by Schiocco** [moneroexamples/onion-monero-blockchain-explorer#318]
The API of https://xmrchain.net no longer works.
E.g. https://xmrchain.net/api/outputsblocks?address=XXXX&viewkey=XXX&limit=5&mempool=1

**Comment by moneroexamples** [comment]
I do not administer xmrchain, but it seems the API was used abused rendering explorer unresponsive and api was switched off: https://github.com/moneroexamples/onion-monero-blockchain-explorer/issues/316

**Comment by Schiocco** [comment]
Ok thanks
