### ISSUE TITLE
A bug in decoding inputs?

### ISSUE THREAD

**Issue by kenshi84** [moneroexamples/onion-monero-blockchain-explorer#32]
I like the new feature of decoding the inputs. While testing it, I'm confused at interpreting the result. Here's an example where
- tx hash: bfb5bd5553dbdcbe9be81703456497aebc7a6af2fd54bbf1a0012b50ed2bb373
- address: 9svHk1wHPo3ULf2AZykghzcye6sitaRE4MaDjPC6uanTHCynHjJHZaiAb922PojE1GexhhRt1LVf5DC43feyrRZMLXQr3mk
- viewkey: 339673bb1187e2f73ba7841ab6841c5553f96e9f13f8fe6612e69318db4e9d0a

![screen shot 2017-01-20 at 11 13 49 am](https://cloud.githubusercontent.com/assets/1090150/22135453/8ec2cd76-df11-11e6-85a8-10c9095c0245.jpg)

![screen shot 2017-01-20 at 11 14 13 am](https://cloud.githubusercontent.com/assets/1090150/22135455/9484eee2-df11-11e6-867c-968f7ed86c6c.jpg)

Why do I see only two keys under the "output public key" list in each decoded input? Also, the second output key in the first input `57dbf8a7bd816b50daeea054bbed8be39e69cd84db13da9be272f0ba71a945f8` was not in the input ring. Is this due to a bug?

**Comment by moneroexamples** [comment]
The `output public keys` list is from tx from which the output come from. Each of them has two outputs in this example. You can click on the tx public keys, e.g, 841ac408edc1e0df9f26212a932876d6481b090fea2916c71856f0f77cb37d1e which will take you to corresponding txs. 

At the moment public key of output in ring signature is not matched with public keys outputs in corresponding txs. Not sure if this is always the case they match? I though that maybe two outputs can be combined to make new output for use in ring signature, which in case the public keys would be different?  

But after thinking now, they should match? I will amend this later, but I still want display non-matched values. This tool I need for the new project: https://github.com/moneroexamples/restbed-xmr as I need to see and be able to check what is exactly happening with inputs and outputs when scaning for them using using address+viewkey only. 

Thanks for testing this:-) Really appreciate your insights!

**Comment by moneroexamples** [comment]
You were right there was bug after all. So I fixed the bug and added matching by public keys of outputs in ring signature and public keys of outputs in mixin's transactions.

For now I keep the changes in PR: https://github.com/moneroexamples/onion-monero-blockchain-explorer/pull/33

As I dont have much time today to make much tests on this.

**Comment by kenshi84** [comment]
Now I understand how to interpret the displayed result. I do see a bug (or simple mistake) in the hyperlinks next to the `from tx of public key:` label. Instead of being properly linked to the said tx pubkey, it's simply linked to the very same page of the transaction with the same tx hash.

Maybe it's a good idea to use transaction ids instead of tx pubkeys for those links since not all websites running this software use the custom LMDB.

**Comment by moneroexamples** [comment]
Thank. You  were right again. I fixed the link and also added tx hash in addition to tx public key. I display tx public keys, instead of only tx hash, as I want to view them easily for checking/debugging key images in the other project.
