### ISSUE TITLE
Feature requestion: display daemon version somewhere on UI

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#35]
Would be cool if it displayed which version of the daemon is providing the backend for the explorer.

**Comment by moneroexamples** [comment]
Hi. Just added it. It looks like this in footer now:

> source code | explorer version: 2017-01-31-a287cb7 | monero version: 0.10.1.0-daf66621

**Comment by Gingeropolous** [comment]
awesome
