### ISSUE TITLE
mdb_env_open: Too many open files

### ISSUE THREAD

**Issue by suhz** [moneroexamples/onion-monero-blockchain-explorer#39]
xmrblocks kill itself. This happen everyday, any clue?

I am on Ubuntu 16.04

>(2017-02-27 22:30:57) [INFO    ] Response: 0x7ef82050dc40 / 200 0
(2017-02-27 22:31:22) [INFO    ] Request: 127.0.0.1:38350 0x7ef820511840 HTTP/1.0 GET /tx/deb7a00f90c4c5e1c09ace7beda54be3f15d2f8139b9c2ac59ce580d467704a5
(2017-02-27 22:31:22) [INFO    ] Response: 0x7ef820511840 /tx/deb7a00f90c4c5e1c09ace7beda54be3f15d2f8139b9c2ac59ce580d467704a5 200 0
(2017-02-27 22:34:53) [INFO    ] Request: 127.0.0.1:38378 0x7ef820515440 HTTP/1.0 GET /tx/b90b7198d86cf321ce47fb0196e1a138b999bbe0786c98d219605aff28dafde0/1
mdb_env_open: Too many open files
(2017-02-27 22:34:53) [INFO    ] Response: 0x7ef820515440 /tx/b90b7198d86cf321ce47fb0196e1a138b999bbe0786c98d219605aff28dafde0/1 200 0
Killed

>(2017-02-28 22:44:16) [INFO    ] Request: 127.0.0.1:56490 0x7fc62c510ec0 HTTP/1.0 GET /tx/d74f3367395934fc3c7ce1d7683631c1dcc8786069f065f40310ac14476cad07/1
(2017-02-28 22:44:16) [INFO    ] Response: 0x7fc62c510ec0 /tx/d74f3367395934fc3c7ce1d7683631c1dcc8786069f065f40310ac14476cad07/1 200 0
(2017-02-28 22:45:16) [INFO    ] Request: 127.0.0.1:56502 0x7fc62c514ac0 HTTP/1.0 GET /tx/4dbeb57856e3a61cf0684fe0f331ff03e97185aa617f95e52fd5c8ce93d1a671
mdb_env_open: Too many open files
mdb_env_open: Too many open files
mdb_env_open: Too many open files
mdb_env_open: Too many open files
(2017-02-28 22:45:16) [INFO    ] Response: 0x7fc62c514ac0 /tx/4dbeb57856e3a61cf0684fe0f331ff03e97185aa617f95e52fd5c8ce93d1a671 200 0
Killed

**Comment by moneroexamples** [comment]
Strange. usually error of too many files open is OS problem. Does your ubuntu server do something else at the same time than running the explorer? Maybe something else is opening files in background? 
Or maybe you have some usually limit imposed on opened files. You can check it using `ulimit -a` command.

**Comment by suhz** [comment]
I run this on a VPS, exclusively for the explorer. I run both explorer mainnet and testnet on same server. Strangely I dont have any issue with the testnet one. Current opened file limit is 1024, maybe I will increase the limit and see if it will resolve the problem.

Currently I am using monero-release and explorer 346855d.

**Comment by moneroexamples** [comment]
Ok. Seems similar to this. Yesterday also was some problem, but with windows 10, only affecting mainnet:

> Actually I might have found a tricky bug potentially related to memory leak (on Windows 8); the explorer runs fine for the first many hours, but after a few days or so it consumes too much memory showing some error message about being unable to parse block number 19243982942748 (i.e. apparently some uninitialized uint value). Also weird enough, this problem doesn't occur with the testnet. Didn't have enough time to look closer into it, but the problem seems to have not existed before my recent commit 1a98ec7. I'll figure out what's going on and report it soon.


https://www.reddit.com/r/Monero/comments/5wq818/protonmail_monero_request_update/decu0fh/

Maybe its same issue and maybe something happened after commit 1a98ec7. What you can do, if you can, is to compile the explorer one commit before that:

```
# if you are in current master then checkout to new branch constructed using the one commit before 1a98ec7
git checkout -b 7d28eec
```

I run the same ubuntu on vps and also have 1024 limit, but I often restart it as I work on other example as well on the same vps. I try to keep it running myself for longer to see how it behaves now.

**Comment by suhz** [comment]
Yes, I run the explorer with custom lmdb database.

ok, I will compile & run the explorer at 7d28eec, and without custom lmdb database.

**Comment by moneroexamples** [comment]
thanks for that. I'm also trying to replicate the issue. Using jmeter to get some requests going and observing the memory. 

Performance improvements are planned. The explorer does not use any caching of blocks, transactions,  template files, nothing. Every request goes through blockchain as if it was totally new. This was not a problem when the explorer was used by only few ppl in darknet. Now in clearnet, the lack of cashing starts to be noticeable. 

But this will happen probably after the newest moneroexample is satisfactory. 

As a funny thing, just before I saw your reply, I made issue for crow: https://github.com/ipkn/crow/issues/220 Need to know if its thread safe or not. This will dictate how the cashing be done for the explorer.

**Comment by suhz** [comment]
After almost 24 hours running explorer on 7d28eec, it seems like it still running till now. It did not kill it self. So, the issue is gone for now.

Good to hear about the performance improvement. Just a suggestion. It would be great if you can make it to return as json, so that I can call it from other app.

Let say if I go to
/tx/2b13655c2aada527a045972a0c5ee061f958e6ffa31c1b08b170b94a055e460d
if will return normal html response.

By adding like **?json=true** at the end will return a json array containing all the data for that page.

**Comment by moneroexamples** [comment]
Thanks for update. I was running jmeter bombarding the explorer with request, nothing too crazy, but seemed ok for the few hours I run it. Anyway, if something happening again please let me know.

Regarding JSON. The new example https://github.com/moneroexamples/openmonero is all about providing custom JSON service for Monero. So I think getting tx details would be more suited there I think, as the example is specially designed with JSON in mind. At the moment it does not have json for tx details, though. But with time it can be added there.

**Comment by moneroexamples** [comment]
Btw, tx for the info about lagging mempool. Just checked what it was doing. I found that json for each tx in mempool was being parsed 5 times:-) lol. There are probably more things can be improved there, but this json thing was the biggest hog. In what state of mind I was to write this is beyond me.

I fixed that to be only one: 

- https://github.com/moneroexamples/onion-monero-blockchain-explorer/commit/89ec6344226ac7836d5319605dcde95d241b692a

I also made a PR to cash template files, so that they are not read from hdd/sdd all the time for each request. 

- https://github.com/moneroexamples/onion-monero-blockchain-explorer/pull/41

And finally I stated looking at caching solution for explorer in `try_lru_cache`  branch. Crow works in asynchronious way in the explorer, I know now, so need to test few things, before making caches everywhere.

**Comment by suhz** [comment]
Really appreciate your work. I am going to update my explorer to the latest commit to test it

**Comment by moneroexamples** [comment]
@suhz 

No problem. I already added caching to mempool and index page in this branch: https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/try_lru_cache2

I'm running it here http://139.162.32.245:8081/ for tests.

**Comment by suhz** [comment]
I tried a820249 for a week, not sure why it killed itself, it just say "*Killed*" in the log .
Now back to 7d28eec again.

**Comment by moneroexamples** [comment]
Thanks for updated. Where there any errors when it killed itself? Like thrown exceptions, or anything?

**Comment by suhz** [comment]
Hmm, there is no error. It just say "Killed". And its a bit weird because it happen with 7d28eec also.  Sorry, there is no information that is helpful this time. 

Just recently, the site is flooded with traffic. I shut the web server temporarily, but leave tor running.

**Comment by moneroexamples** [comment]
Thanks. If something, please let me know.

**Comment by suhz** [comment]
I'll close this. 

The problem seems to have been resolved since c7d84b0 with monero 0.10.3.1-release. I am running it for almost 3 weeks now.

**Comment by moneroexamples** [comment]
Thanks. If something else is happening, please let me know.

**Comment by moneroexamples** [comment]
Hi.

Before you asked about json api. It has just been added if you still interested in it. Info is in readme of this branch:
