### ISSUE TITLE
block size calc seems off

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#4]
http://107.172.25.35:8081/block/1123800

the header says its Block size [kB]:	0.8027

but the transactions clearly add up to more.... thoughts?

**Comment by moneroexamples** [comment]
A block structure contains only hashes of txs, not entire txs data. So its small. But then when you start fetching individual txs based on these hashes, they have their own data, like list of input and outputs, extra field, etc. Thus they add up to much biger size than just a block size.
