### ISSUE TITLE
explorer version: 2017-03-04-a820249 is laggy

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#43]
Apparently this version is eating a lot of CPU.

**Comment by moneroexamples** [comment]
It is. There was a performance bug with mempool (5 times parsing json for each tx, for no reason):

- https://github.com/moneroexamples/onion-monero-blockchain-explorer/issues/39#issuecomment-283905473

This was already fixed. Also, new branch was made for adding caches, to improve perforce. Short info here:

 - https://github.com/moneroexamples/onion-monero-blockchain-explorer/issues/42

This branch is running here: http://139.162.32.245:8081/

Index and txs pages have added short info at the bottom, on timing when tx details are taken from cache, and when are constructed from sctach. 

For example, first reading (so not in cache) of this tx: http://139.162.32.245:8081/tx/e03f48a6f1d4604a27440cddf1e4f4182338c836d33a50e67b43a5ffec45a4ec

- Tx details construction time: 0.4323 s

Second reading (from cache now)

- Tx details construction time: 0.0014 s

**Comment by Gingeropolous** [comment]
so..... run that branch? Or wait until you think its ready???

**Comment by moneroexamples** [comment]
I wouldnt run that branch yet. But current master should be ok. I have no new reports about leaking memory or lagging. In the master, the mempool has been fixed, and it already preloads template files.

**Comment by Gingeropolous** [comment]
i compiled and am running it. I just dropped the binary into the already functioning folders. It is still laggy (checkout xmrchain.net )

**Comment by moneroexamples** [comment]
Thanks. I checked now, and for me it seems to work ok. But then there are only two txs in mempool now. I try later, when there is more mempool txs. Maybe it still lags a bit when parsing json for massive mempool (e.g., 100 txs or more). Or maybe xmrchain got very popular now, and receives a lot of visits adding to lag? 

The caches should help later on. You can check cached branch here: http://139.162.32.245:8081/ At bottom of index and tx pages, I added small timer, to show differences in txs details construction with and without cache. 

As a side note. If you just drop binary into old folder with template, your templates will be outdated. For example, Tx pusher | Key images checker | Output keys checker links on xmrchain are dead. These have been made optional, and are off by default. Need to enable them with xmrblocks program options to have them.

**Comment by Gingeropolous** [comment]
Its unreponsive as I write, and this is what the systemd log says

Mar 14 19:45:55 iof1006e clearnet_exp.sh[22293]: So lets try to search there for what we are after.
Mar 14 19:46:10 iof1006e clearnet_exp.sh[22293]: (2017-03-14 19:46:10) [INFO    ] Request: 127.0.0.1:33358 0x7f75502697c0 HTTP/1.1 GET /search
Mar 14 19:46:10 iof1006e clearnet_exp.sh[22293]: invalid hash format: <https://xmrchain.net/search?value=41vJdWkFFPPAvhTF9EybUca14R76sRnDX48tLGtgB82ZdFksF1fJUaNMQc2i76DFVcABrkcuxU2xdF7vubUGhhbkGkfWuNR>
Mar 14 19:46:10 iof1006e clearnet_exp.sh[22293]: Cant parse a key (e.g. viewkey): https://xmrchain.net/search?value=41vJdWkFFPPAvhTF9EybUca14R76sRnDX48tLGtgB82ZdFksF1fJUaNMQc2i76DFVcABrkcuxU2xdF7vubUGhhbk
Mar 14 19:46:10 iof1006e clearnet_exp.sh[22293]: Cant parse tx hash: https://xmrchain.net/search?value=41vJdWkFFPPAvhTF9EybUca14R76sRnDX48tLGtgB82ZdFksF1fJUaNMQc2i76DFVcABrkcuxU2xdF7vubUGhhbkGkfWuNR
Mar 14 19:46:10 iof1006e clearnet_exp.sh[22293]: invalid hash format: <https://xmrchain.net/search?value=41vJdWkFFPPAvhTF9EybUca14R76sRnDX48tLGtgB82ZdFksF1fJUaNMQc2i76DFVcABrkcuxU2xdF7vubUGhhbkGkfWuNR>
Mar 14 19:46:10 iof1006e clearnet_exp.sh[22293]: Cant parse a key (e.g. viewkey): https://xmrchain.net/search?value=41vJdWkFFPPAvhTF9EybUca14R76sRnDX48tLGtgB82ZdFksF1fJUaNMQc2i76DFVcABrkcuxU2xdF7vubUGhhbk
Mar 14 19:46:10 iof1006e clearnet_exp.sh[22293]: Cant parse blk hash: <d09bff76757f000028a92650757f000030a8ff76757f0000cf09cab87a7f0000>
Mar 14 19:46:10 iof1006e clearnet_exp.sh[22293]: Custom lmdb database seem to exist at: /home/monerosupport/.bitmonero/lmdb2
Mar 14 19:46:10 iof1006e clearnet_exp.sh[22293]: So lets try to search there for what we are after.

**Comment by moneroexamples** [comment]
Thanks.

The last thing before freeze/crash seems to be accessing custom lmdb database. You can disable it simply by renaming `lmdb2` folder or removing it, e.g., 

```
mv /home/monerosupport/.bitmonero/lmdb2 /home/monerosupport/.bitmonero/lmdb2_old
```

If you do it, then off course, need to kill its process so that it does not try to update it.

Maybe this is causing problem, and I cant cant cache it as on my vps I dont run custom lmdb. Simply have no space for it. Also I think I will be slowly fazing it out. For open monero project I already ditched it, and replaced with mysql.

Regarding general lag. There were more updates to branch https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/try_lru_cache2

For example, generation of timescale and mixin details have been made optional. Which greatly improves processing of large txs, even without caches, 

- http://139.162.32.245:8081/tx/fae5b3f53a4c6e8cd6111535847acf2556e7f334861f9ad8107246a3bb3387e9

As can be seen, timescales and mixin details, e.g., mixin of mixins, their age are not present.

**Comment by Gingeropolous** [comment]
i'll go ahead and close this.......
