### ISSUE TITLE
block height and key_offsets

### ISSUE THREAD

**Issue by moneroexamples** [moneroexamples/onion-monero-blockchain-explorer#44]
hi,
Im programming my own explorer just for fun to understand monero and I had looked up much in your explorer and in www.moneroblocks.info .
it seems like your explorer has a small indication error: if you click on a transaction from e.g. block #x, then this transaction says that it's in block #(x-1).
and I had issues with key_offsets, your explorer shows other inputs than moneroblocks.info in every transaction. so I think that one of you two are doing a wrong indexing. but I dont know how to verify key_offsets, so I cannot say you who is wrong. if you know and like to help me, I would love to hear how I can check them.
I dont have a github account (Im not a real programmer, just sometimes for fun) so thats why I write you here. I hope this is okay.

by /u/-yara

**Comment by moneroexamples** [comment]
Thank you, very good observations. I made issue from this, for future reference:

- https://github.com/moneroexamples/onion-monero-blockchain-explorer/issues/44

Block height should already be fixed. The fixed version is running here (development server): http://139.162.32.245:8081/

The key images is more problematic to test, but I tested it quickly now (you can repeat) and it seems my offsets are correct. I did as follows, on both mainnet and testnet. But here I provide you with testnet info so you can check. Basically, I checked spending estimations using view key. Not sure you know, but the explorer also estimates possible spending using view key. So I used that to check, on the assumption that if key images are wrong, the estimation would fail. I took my old spending (outgoing) tx on testnet:

1. Go to http://139.162.32.245:8082/tx/9d17084091beedc55c8a0cd342e441b7c0d89eeca25ac151b4b91fe1e12051e7

2. Input my testnet address and viewkey: 9wUf8UcPUtb2huK7RphBw5PFCyKosKxqtGxbcKBDnzTCPrdNfJjLjtuht87zhTgsffCB21qmjxjj18Pw7cBnRctcKHrUB7N and 3561b7f41a5a22c85ad8fd3016255cd7ce4bf3ec063dbf41e6e5a10ba0e5db07

3. Press decode outputs

4. Press Show decoded inputs

5. Since this is my outgoing tx, I know for sure what I sent and that at least one of the outputs (mixins) in each key image must be mine. So using this, I can confirm that 2.450000000000 is the exact spending in that tx I made. If the key images were incorrectly decoded, the spending estimation would not work, and probably would not be even shown at all.

The same can be done on mainnet (http://139.162.32.245:8081 or https://xmrchain.net). You can try it using your own spending txs. 

Ideally there should be some better way to test it, but for quick tests this method seems be sufficient. 
 
If have any questions, please feel free to ask.

**Comment by pinheadmz** [comment]
I'm encountering a similar error requesting `https://xmrchain.net/api/networkinfo` -- the height seems to be off by 1

**Comment by moneroexamples** [comment]
Thanks. I will look into it next week. In the meantime, could you provide example of incorrect output, and what would be expected correct data?

**Comment by pinheadmz** [comment]
You can see the discrepancy with the other API calls (see below). Other XMR block explorer websites seem to agree with the `transactions` API call but I don't know if they are using buggy APIs as well! I will sync up my own full node and verify which is actually correct :-)

`https://xmrchain.net/api/transactions`:

**"hash":"91fb4fd2194aa0838d1b414c33981a96116d31fad1e1e329161ea2a113aa2fe8",
"height":1402624**

`{"data":{"blocks":[{"age":"00:04:18","hash":"91fb4fd2194aa0838d1b414c33981a96116d31fad1e1e329161ea2a113aa2fe8","height":1402624,"size":54724.0,"timestamp":1505840315,"timestamp_utc":"2017-09-19 16:58:35","txs":[{"coinbase":true,"extra":"015a8490e981e831bc208a35c75984afb683423e29c1e7dfe759dabbb8554f60490208000000042ffe3f96","mixin":0,"payment_id":"","payment_id8":"","rct_type":0,"tx_fee":0,"tx_hash":"99a2bcd4e3457a86cc453efd56c3047e8ea167388d16e407c1d7c7c933fbe98e","tx_size":95,"tx_version":2,"xmr_inputs":0,"xmr_outputs":6495254176815}.........`

`https://xmrchain.net/api/networkinfo`:

**"height":1402625, ... 
top_block_hash":"91fb4fd2194aa0838d1b414c33981a96116d31fad1e1e329161ea2a113aa2fe8"**

`{"data":{"alt_blocks_count":19,"block_size_limit":600000,"cumulative_difficulty":3545696058147434,"current":true,"difficulty":28876547417,"fee_per_kb":254980000,"grey_peerlist_size":0,"hash_rate":240637895,"height":1402625,"incoming_connections_count":46,"outgoing_connections_count":275,"start_time":1505530463,"status":true,"target":120,"target_height":1402619,"testnet":false,"top_block_hash":"91fb4fd2194aa0838d1b414c33981a96116d31fad1e1e329161ea2a113aa2fe8","tx_count":1665728,"tx_pool_size":16,"tx_pool_size_kbytes":214318,"white_peerlist_size":1000},"status":"success"}`

**Comment by pinheadmz** [comment]
OK I can confirm with my own node that `transactions` is correct and `networkinfo` is off by one:
```

{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "block_header": {
      "block_size": 54724,
      "depth": 109,
      "difficulty": 28852040163,
      "hash": "91fb4fd2194aa0838d1b414c33981a96116d31fad1e1e329161ea2a113aa2fe8",
      "height": 1402624,
      "major_version": 6,
      "minor_version": 6,
      "nonce": 7422,
      "num_txes": 4,
      "orphan_status": false,
      "prev_hash": "4a5024be56964f069b3a309ccfbf1a7bdc6bfcd872f7ab8ba2e1204ed92ac926",
      "reward": 6495254176815,
      "timestamp": 1505840315
    },
    "status": "OK"
  }
}
```

**Comment by moneroexamples** [comment]
I see. I think this comes from monero "strange" naming conventions. The height in the `networkinfo`, is 
height of blockchain, not the height of the last block. Thus its always higher by 1 as the block heights are counted from 0. 

This is same as on http://moneroblocks.info/,  where in the page's header you see height, which will be always greater by one from the height of the last block.

Does this answer your question, in case I misunderstand it?

**Comment by pinheadmz** [comment]
Ah thanks, didn't know that about Monero!
