### ISSUE TITLE
Feature request - look up by date

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#5]
Can you pretty please add a feature to look up a block by the timestamp?

Timestamp [UCT]: 2016-11-13 08:51:43

I dunno which format would be best, but the data seems to be in there.

**Comment by moneroexamples** [comment]
Good idea. I will look into it. I already have code for estimation of block height from a date, so maybe can use this. Could also add the stamp to the custom lmdb database, for super fast and exact search of block.

**Comment by moneroexamples** [comment]
Just marged it to master.
https://github.com/moneroexamples/onion-monero-blockchain-explorer/pull/11

The supported datetime format is 2016-11-13 08:51:43 . If the block with exact timestamp does not exist, the first block with higher timestamp is returned.

For this to work, the custom lmdb database must be up to date, and the timestamps are taken from them. In Monero blockchain, you cant search blocks based on timestamps.

Also UTC timezone were fixed, so now the dates and times shown are UTC, unlike before.

**Comment by Gingeropolous** [comment]
```2016-11-13 08:51:43```

i'll probably find out once I compile and test it, but can you input substrings of the above?

i.e., 2016-11-13 08:51:43 would get a specific block, but 

2016-11-13 08:51 would return any block found in that minute

and 2016-11-13 08 would return any block found in that hour, or blocks found starting at that hour. 

2016-11-13 would return blocks found starting that day  
etc etc

**Comment by Gingeropolous** [comment]
> For this to work, the custom lmdb database must be up to date, as the timestamps are taken from it. In Monero blockchain, you cant search blocks based on timestamps.

OOOOH im an idiot. By up to date, you mean recompile. Not simply that the database on the server is currently up to date with the blockchain.

**Comment by moneroexamples** [comment]
Nope, just having current blocks. No need to recompile or recreate it.

**Comment by Gingeropolous** [comment]
hrm... though there are a lot of changes to lmdb-cpp since I compiled last apparently

**Comment by moneroexamples** [comment]
The datetime search has been extended and its ready for testing.

- `2015-04-15 12:02:33` searches for block of this timestamp or first next one.
- `2015-04-15 12:02` searches for all txs made in the given minute
- `2015-04-15 12` searches for all txs made in the given hour
- `2015-04-15` searches all txs made in that day (only up to 500 txs are displyed though).

SInce the custum lmdb database is used for the searches (its not possible to search for this effeciently in monero blockchain), lmdb must be running and keeps its records up to date with blockchain.

**Comment by Gingeropolous** [comment]
sweeeeeet.

**Comment by moneroexamples** [comment]
Let me know if there are some problems with it or something else is required.

**Comment by moneroexamples** [comment]
If there are no further question or issues, I will close this issue. Please feel free to re-open if needed.
