### ISSUE TITLE
Integrate Monero as Submodule similar to Monero-Core

### ISSUE THREAD

**Issue by dternyak** [moneroexamples/onion-monero-blockchain-explorer#54]
It would be great for higher-level language developers (like me) who aren't as familiar with C++ to be able to build the blockchain explorer with a one-time script.

Could something similar to the [build.sh](https://github.com/monero-project/monero-core/blob/master/build.sh) that Monero-Core has be implemented? This appears to rely on having Monero as a submodule, which I think would be beneficial even without the build script.

Eager to hear your thoughts on this.

**Comment by moneroexamples** [comment]
Thanks. The work to simplify the build is already undertaken, but not yet in the explorer. OpenMonero project is already using [FindMonero.cmake](https://github.com/moneroexamples/openmonero/tree/master/cmake) module of cmake to making building a bit easier. My aim is to make it as easy as building `cpp-ethereum`, and in fact [FindMonero.cmake](https://github.com/moneroexamples/openmonero/tree/master/cmake)  is already based on `cpp-ethereum` cmake modules. When it will be ready, I don't know unfortunately. First need to finish few things with explorer, openmonero, also trying to upgrade [custom lmdb database](https://github.com/moneroexamples/lmdbcpp-monero) to bring it back to the explorer. Lots of things are happening, only time is needed.

**Comment by dternyak** [comment]
Awesome. The work you're doing is really valuable, and I'm excited to see it to continue to progress. 

If you ever run into a need for funding, please make a FFS and I will be the first to back it.

**Comment by moneroexamples** [comment]
Building process has been simplified from this commit: https://github.com/moneroexamples/onion-monero-blockchain-explorer/commit/4fc33137de2dbd1dc02f5db6a80734143f414ee8

Now only downloading and compilation of monero is needed. Its not required anymore to copy anything to `/opt/monero-dev` or any other location. 

New, hopefully easier instruction are in README. 

This has also been added to [pure_css_try](https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/pure_css_try) branch.

If you have some questions, comments or problems, please let me know.
