### ISSUE TITLE
get network info

### ISSUE THREAD

**Issue by suhz** [moneroexamples/onion-monero-blockchain-explorer#59]
Hi, I've notice a recent commit that provides Monero Network info via json api. 

I am wondering if I can get and display that info in index2.html or header.html?

**Comment by moneroexamples** [comment]
Was thinking same, but not yet get time into making it. I will add it soon. Only coin emission will be missing, but there is no "easy" way to get this number without actually doing the calculations, storing the value, and keep updating it with each new block.

**Comment by suhz** [comment]
Cool, I can wait :-)

I would love to help, but I think I need to learn how to code c++ first 💃

**Comment by moneroexamples** [comment]
No problem. You are already helping lots by testing and running the explorer. If you want to help more, you can also have a look, and play around with open monero (http://139.162.32.245:81), and report issues or bugs.

**Comment by moneroexamples** [comment]
I added basic network info: http://139.162.32.245:8081/

Its not yet merged into master branch. Still thinking if there is an efficient way to get current emission monero amount.

**Comment by suhz** [comment]
wow nice, that was fast. but it will only available in index page right?

Thanks. I will try play around with open monero see if I can find anything.

**Comment by moneroexamples** [comment]
Thanks. the emission calculation is not complied yet. For now I made something quickly to check if its feasible, but its not yet usable for end users. Its not parametrized, not working with testnet, and need more testing. 

Any feedback on open monero appricated. if you dont have testnet monero, I can sent some for you.

**Comment by suhz** [comment]
I think I still have some testnet monero.

**Comment by moneroexamples** [comment]
So I think network info and emission are good to go and are running here: http://139.162.32.245:8081/. Currently they are still in this branch:

https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/add_network_info_front_page

Emission by default is disabled. The paragraph was written how to enable it and how it works:

- https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/add_network_info_front_page#enable-monero-emission

If you want, you can test it using that branch, and see how it works, before I marge to master. 

There were also other changes, such as mempool handling for the front page was made as async call now, to avoid blocking the entire page if there is lots of mempool txs, like [yesterday](https://np.reddit.com/r/Monero/comments/6d6rc8/meanwhile_mempool_is_at_45mb_lots_of_large_txs/), mixn was renamed to ring size, mempool_error.html  and json `/api/emission` were added.

p.s. Nice visual upgrade to https://explorer.xmr.my/ :-)

**Comment by suhz** [comment]
Nice, I am going to try this! on new vps, and try to put the network info into my "new design"  :)

Thanks, I plan to merge those css and template with yours, but I still haven't finish converting the form part. Looks too big to me.

**Comment by suhz** [comment]
btw, what is " Alt blocks: 0 " ?

**Comment by suhz** [comment]
I notice that "network info" disappear sometimes, can you make it show the last available network info, probably from cache if latest one cant be display instead of not showing at all?

**Comment by moneroexamples** [comment]
Thanks for feedback.

Alt blocks are alternative blocks. You get them when two or more blocks are mined at the same time.

Network info disappears sometimes as it times out. Keeping the network info in cache and show older version if current times out, is very good idea. Ideally I would put it into emission monitoring thread, so the thread would just query the network info once every minute, and this info would be shared between all requests. At the moment, every html request results in rpc call to deamon for the network info. Doing similar for mempool would also be very beneficial. 

As quick counter measures I increased timeout to 2 seconds, from 1 seconds, and changed "Alt blocks" to "Alternative blocks no". Showing old version or using emission thread requires little more work. I will do it, hopefully, over this weekend.

**Comment by moneroexamples** [comment]
Updated the network info, and now if it times out, previous values will be shown. If the previous values are older than 1 block time (2 min), age of the info is also shown so that a user knows that he is looking at older data. To control mempool and network info timeouts, two `xmrblocks` options were added:
```
  --network-info-timeout arg (=1000)    maximum time, in milliseconds, to wait 
                                        for network info availability
  --mempool-info-timeout arg (=5000)    maximum time, in milliseconds, to wait 
                                        for mempool data for the front page
```
These updates were done, as before, to this branch: https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/add_network_info_front_page

Let me know how it works now, if you can. Also, did you try emission monitoring?

**Comment by suhz** [comment]
Thanks for the update. Looks much better now without missing network info.

I did try emission monitoring.  But the emission number on my explorer is different than your dev site.
http://202.5.19.11:8081/ is having different number than http://139.162.32.245:8081/

Is it suppose to be like that?

**Comment by moneroexamples** [comment]
I see, there is small difference in amount. I compared my dev server and my node: http://i.imgur.com/jbsLO56.jpg The amount my dev website shows agrees with my daemon as can be seen. You can check your node: `print_coinbase_tx_sum 0 1320363` the command is time consuming, as it goes through all blocks. Maybe your node's amount is somehow different then my node, thus difference on the websites?

p.s. more and more impressed with look and feel of your explorer.

**Comment by suhz** [comment]
I've tried  `print_coinbase_tx_sum 0 1320545` and it just stuck there, with 100% cpu for 7 hours. I give up. 

Maybe I will try on my other machine see if it give anything.

**Comment by moneroexamples** [comment]
7 hours seems way too long. for me it takes about 30 min.

**Comment by suhz** [comment]
Unfortunately, I dont have any other available machine to test that.

It is only a small difference, can we assume it it ok? ¯\_(ツ)_/¯

**Comment by moneroexamples** [comment]
The difference seems constant at 0.02 xmr. On testnet you also observe a difference and lag with `print_coinbase_tx_sum`?

**Comment by suhz** [comment]
yes, same thing.  I guess maybe because my vps don't have enough cpu or memory resource for that.
I tried on other vps, it killed monerod in few minutes.

**Comment by moneroexamples** [comment]
Thanks.  So at least testnet agrees. I will keep monitoring the emission rates though, and check if they diverge more. 

p.s. you could restart the emission on mainet, if you want, just to check if it is reproducible difference. Simply stop the explorer (Ctr+C), remove `~/.bitmonero/lmdb/emission_amount.txt` and start it again. This will recalculate the emission from scratch.

**Comment by suhz** [comment]
I restart the emission on mainnet as you suggest, now the emission is equal to your dev explorer. 

![image](https://cloud.githubusercontent.com/assets/5063489/26615381/0ab793aa-45f9-11e7-8c47-a3d0a5602646.png)

**Comment by moneroexamples** [comment]
That's good that it agrees now. But still curious what might have caused the difference.

**Comment by suhz** [comment]
I'll close this, as the feature has been merged into master.

Thanks @moneroexamples

**Comment by moneroexamples** [comment]
@suhz 

I think your node is stuck again. Yesterday some users experienced stuck nodes at the same time as yours: https://www.reddit.com/r/Monero/comments/8h4rc1/whats_happening_at_block_1565706_or_1565707_for/

**Comment by moneroexamples** [comment]
@suhz 

Hi. i was updating url links of the explorer, and noticed that your nodes (onion and mainnet) are down. Not sure if you still maintain them or not, so just wanted to verify this with you.
