### ISSUE TITLE
Full page not delivered on i2p

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#7]
I don't know if its crow, the explorer code, or the i2p functions that are making this weird. But basically, if you visit monerotools.i2p , sometimes the page isn't rendered, and its because the html it receives is partial (usually the footer is missing).

Perhaps there's a way to make crow pause before it finally servers up the page? Or to check that the footer is attached to the final product?

**Comment by moneroexamples** [comment]
If there is missing template file, explorer will just use empty string, so if tempate paths are wrong it will just skip them. But you should see a message in crow console output when this happens. The mesage starts with `File does not exist: `.

**Comment by Gingeropolous** [comment]
I didn't see that error. I'm using the exact web page setup you have in the template - no modifications.

**Comment by moneroexamples** [comment]
I will try accessing `monerotools.i2p` later today, and see how it goes.

**Comment by moneroexamples** [comment]
Left it overnite and now it works. And wow! Its fast! My faster then my onion version:-) 

I see that index stops loading by the end. All templates are loaded fine as on other pages they are ok. My guess is that index page is timeing out on i2p and it just servers what ever has been processed by that time.

I reduced no tx of on index page from 50 to 25. I also fixed the bug that when you click on block number on index, it may not show up.

Can you check now with the changes?

**Comment by Gingeropolous** [comment]
I checked, and the main page worked. But then this page didn't work:http://monerotools.i2p/tx/b3b3b13cae01a0c5f11d78f0aad729924fedcb46ad0bbaa73da33b31aff33e35

even though the full html loaded (it has the footer). I'm using chromium on ubuntu - perhaps chrome is just less tolerant of messed up html / css? I made a commit based on an analysis of the html of that page from: https://validator.w3.org/ .

I didn't test it though. i should really do a proper fork and work on that as opposed to using the GUI github. ah well.

**Comment by moneroexamples** [comment]
If its working on localhost, i.e., without using i2p, than its ok. I also use chrome and firefox on tor, so the browser is not an issue. Your linked work for me in i2p: http://i.imgur.com/YLapSqS.png

But then key images file did not load in full (zoom reduced to fit everything in one screenshot): http://i.imgur.com/eTm10ye.png

This seems like timeone issue for i2p. Maybe there is some setting to allow for more time for page generation in i2p or bandwitch linit per page? serve page when its full

**Comment by moneroexamples** [comment]
One other possibility that comes to my mind now is that some time ago I added blockiing some tor robots in main.cpp. Maybe it makes issues for i2p. Just in case I just removed it from main.cpp:
https://github.com/moneroexamples/onion-monero-blockchain-explorer/commit/04feb4448fab78dac67d7db16861f2697d7add8c

**Comment by Gingeropolous** [comment]
HRm. I got the raw even after the latest commit. But then I took that raw, saved it as .html and then opened it with firefox. So I think its just that chromium sucks for some reason.... unfortunately I have chromium setup as my i2p browser. Time for another browser I guess.
