### ISSUE TITLE
File not found src/monero_headers.h

### ISSUE THREAD

**Issue by sflyer** [moneroexamples/onion-monero-blockchain-explorer#70]
I'm have problem on make:
all files, included in src/monero_headers.h not found. Folders like cryptonote_core/ or blockchain_db/ not exist too. 
What it is files and how create\where download it? Thanks.

Example error 
`/home/user/onion-monero-blockchain-explorer/src/monero_headers.h:19:37: fatal error: release/version/version.h: File not found
`

**Comment by moneroexamples** [comment]
Did you checkout and compiled v10.3.1 of monero as shown in the explorer's readme, i.e., `git checkout -b last_release v0.10.3.1`. If you use latest monero dev version, explorer from the master branch wont compile with it. 

Alternatively, to work with latest dev monero branch, you need to use this explorers development branch: https://github.com/moneroexamples/onion-monero-blockchain-explorer/blob/update_to_current_monero/README.md

What OS do you use, btw?

**Comment by sflyer** [comment]
My OS - ubuntu server 16.04 x64
Problem solved - dont compile as root, use another user.

**Comment by moneroexamples** [comment]
Ok. So I close the issue if its solved. If something new happens, please feel free to make new issue or reopen this one.
