### ISSUE TITLE
Warning / Error on starting

### ISSUE THREAD

**Issue by bsbits** [moneroexamples/onion-monero-blockchain-explorer#71]
When I run` ./xmrblocks `

I get this error

`2017-07-18 02:36:44.741	    7f2acbeb2780	INFO 	global	contrib/epee/src/mlog.cpp:145	New log categories: *:WARNING,net:FATAL,net.p2p:FATAL,net.cn:FATAL,global:INFO,verify:FATAL,stacktrace:INFO
`
but the service loads on 8081

Same case when I run `monerod --detach`, I get this error

```
2017-07-18 02:38:30.704	    7fcdc60d9740	INFO 	global	contrib/epee/src/mlog.cpp:145	New log categories: *:WARNING,net:FATAL,net.p2p:FATAL,net.cn:FATAL,global:INFO,verify:FATAL,stacktrace:INFO
2017-07-18 02:38:30.704	    7fcdc60d9740	INFO 	global	src/daemon/main.cpp:282	Monero 'Wolfram Warptangent' (v0.10.3.1-release)
Forking to background...

```

**Comment by moneroexamples** [comment]
I think this is just a least of all log level categories. not actual error. so is the explorer working when you go to a browser?

**Comment by bsbits** [comment]
Sadly no, there is an issue when I start monerod daemon.

I will attempt installing Monero via docker then retry installing the explorer.

Just to make sure, monero have to sync with the full blockchain for xmrblocks to run ?

**Comment by moneroexamples** [comment]
If monerod has problem, can make issue https://github.com/monero-project/monero

No need to have full blockchain for xmrblocks. It should work with un-synced ones as well. But obviously you will not have access to recent blocks which your blockchain does not have.

**Comment by bsbits** [comment]
What I want to accomplish is get notified via RPC whenever there is a new block and whenever there is an upcoming transaction to a watchonly wallet.

The block notification will allow me to validate the shopper purchase when it reaches 6 confirmations.

I am hoping xmrblocks can offer me all these functionalities

**Comment by moneroexamples** [comment]
A normal monero wallet have RPC interface. It should have any RPC to get balance of your wallet and details of any incomming txs. When you download monero or compile it yourself you will get binary called `monero-wallet-rpc`. It should do all this.

But if not, `xmrblocks could also be used`. Current xmrblocks has this API call: https://github.com/moneroexamples/onion-monero-blockchain-explorer#apioutputstxhashtx_hashaddressviewkeytxprove01

This is for checking an individual tx, not block. But If needed I can add API for checking one or last few blocks for your a users txs.

**Comment by bsbits** [comment]
`monero-wallet-rpc` can indeed notify me for an incoming transaction, but only when it hits the walllet (not when it gets 6 confirmations).
Besides, if `monero-wallet-rpc` crashes, I will miss the transaction - RPC calls do not have retry feature.

can xmrblocks monitor an address and send an RPC notification whenever that address receive coins ?

**Comment by moneroexamples** [comment]
xmrblocks by itself cant monitor blocks and sent out notifications. You would have to call its API yourself in a loop, e.g., every 10 seconds, and then check the results if there is something to you.
