### ISSUE TITLE
Show privacy-relevant recent transaction stats

### ISSUE THREAD

**Issue by pinkbrad** [moneroexamples/onion-monero-blockchain-explorer#83]
It would be really swell if we could quickly see a summary of privacy relevant stats: ringsize, payment ID presence, fee (as the multiplier). Ideally this would show the top 10 combinations. It doesn't help to know ringsize 41 is popular, if the fees are a strange value only used by one type of wallet. And maybe it should throw out uncommon in/out values. For instance the group doing a bunch of 38/38 transactions. It does not matter if they started to use ringsize 9, an outsider will never fit in with those transactions.

Using the last 2-3 days of transactions is enough. Although maybe it should separate by time of day eventually if it results that certain attributes are more common at specific times. For instance a group using a certain config might only be online during the UK daytime.

The end goal is to allow people to stay more private by sticking with a couple of the most common publicly-visible attributes, yet be able to take advantage of larger ringsize when feasible.

**Comment by moneroexamples** [comment]
Thanks for suggestion. At the moment the explorer does not have any database to store any historical data (except emission rate, if explicitly enabled), thus it does not have any stats.  

For stats, probably would be better to do dedicated services, with javascript for nice graphs, database to store historical data, etc, such as this one (discontinued currently): http://monerostats.com/charts/?type=basic

Also some current stats about ring sizes are here: http://moneroblocks.info/stats/ring-size

Having said that, it could be good idea to add some very basic stats to the explorer, from last 2-3 days, like you said. I will think about this, but at the moment cant specify any time frame for this development. I will leave the issue open to indicate a possible new feature to be added to the explorer in future. 

p.s.
Regarding payment ID. Indication about payment ID will be probably added before the stats to the list on the index page. `nonrct` data will be removed and replaced with whether a tx has encrypted or encrypted payment id, or lack of the id.

**Comment by moneroexamples** [comment]
I modified other project, and added ring members basic stats, example outputs is here

https://github.com/moneroexamples/transactions-export#searching-txs-which-use-our-outputs-as-ring-members-and-their-frequency

Its a command line tool, nothing online or with fancy gui. But i think it does the job, of at least, showing how ring members frequencies can be obtained as basis of future developments
