### ISSUE TITLE
This bit of code actually links to "localhost:8888" instead of the public link

### ISSUE THREAD

**Issue by BranndonWork** [moneroexamples/onion-monero-blockchain-explorer#93]
https://github.com/moneroexamples/onion-monero-blockchain-explorer/blob/e6d0d8d86061ee8a5cd3b6f53f1e1b91733ba5cc/src/templates/my_outputs.html#L80

Example URL in my browser http://localhost:8888/myoutputs/redacted/redacted/redacted

I'm running it from the public site https://xmrchain.net/

**Comment by moneroexamples** [comment]
xmrchain is running bit older version of the explorer; from 2017-09-07. Since then this was fixed. Can check newer versions, e.g., https://moneroexplorer.com/ from 2017-10-14 or its bleeding edge at http://oculus.serveo.net/
