### ISSUE TITLE
[Feature request] Client-side tx checking

### ISSUE THREAD

**Issue by stoffu** [moneroexamples/onion-monero-blockchain-explorer#97]
The "decode outputs" / "prove sending" tools are very useful as they allow users to conveniently check if their transactions have been processed as intended. However, in the current implementation, the user's secret key (the view secret key or the tx secret key) is sent to the server in order to perform the check on the server side, which is quite undesirable because a malicious entity running the explorer could keep record of all the submitted secret keys and abuse the knowledge.

Giving out one's view secret key is particularly problematic, as it alone enables guessing outgoing transactions of that particular wallet quite accurately, as I explained here:

- https://www.reddit.com/r/Monero/comments/7plvvd/monero_observer_new_issue_jan_2_8_weekly_monero/dsiak2l/

(The very tool in the above explanation is provided by this explorer.)

It'd be much more desirable if this check could be performed purely client side, similar to @luigi1111's implementation in JavaScript:

- https://xmr.llcoins.net/checktx.html

Could you please consider integrating the above code into the explorer, so that the above security risk can be circumvented?

Thank you!

**Comment by moneroexamples** [comment]
I was thinking about this myself a bit, and think it would be good addition. Probably I would made it optimal to enable js-version of the explorer, so that js-free is still default, but who overruns the explorer could enable using js for decoding/proving txs. All the code for this could be adopter from xmr.llcoins.net and/or openmonero (mymonero) projects.

**Comment by moneroexamples** [comment]
I started this development. It is in this branch if someone interested:

https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/js_for_decoding_proving

**Comment by moneroexamples** [comment]
I think first working version for js is ready for testing. My testnet and mainnet explorers with js enabled are here: http://nimis.serveo.net and https://oculus.serveo.net/. They are bit slow, but for now, I dont have better server to host them.

**Comment by stoffu** [comment]
Confirmed it working! Thank you so much for improving the ecosystem!

**Comment by moneroexamples** [comment]
Cool. Thanks. Still some polishing is required, but I dont expect making major changes.

**Comment by stoffu** [comment]
Closing as it's implemented and merged in #98. Thank you!

**Comment by moneroexamples** [comment]
No problem :-)
