### ISSUE TITLE
Localhost link on live page

### ISSUE THREAD

**Issue by reidi2000** [moneroexamples/onion-monero-blockchain-explorer#99]
**Page URL**: https://xmrchain.net/myoutputs (404 for direct access, follow steps below)
**Ease**: Easy
**Reproducibility**: 100%
**Severity**: Low

**Steps:**

1. Aquire a transaction key, either one of your own or a random one from the home page and append this to 'https://xmrchain.net/tx/{txID}'. 

> Example: [A random transaction](https://xmrchain.net/tx/ba3027f35b1b626a1d9ed1ffcc27b83f452d660a4c3d1c6b0f5109f5a5fc7876)

2. Scroll down, find the 'Decode Outputs' tab, and fill in the Monero address and respective view key for the transaction - it doesn't matter if it isn't a transaction made to yourself.

3. Above the footer of the page, there will be a clickable link to 'link to this page'. This link has a target of a localhost machine on port 8888. This must've slipped through from production to release, not allowing for users to create a permalink. Replacing localhost:8888 with the FQDN of the site works perfectly. 

![minorissue](https://user-images.githubusercontent.com/20614738/35593269-5338024e-0607-11e8-9684-ece04b76a557.PNG)

**Comment by moneroexamples** [comment]
The issue has been already addressed, but xmrchain is running explorer version from 2017-09-07.  In later versions, e.g., https://moneroexplorer.com from 2017-10-14, the link should be correct.

**Comment by reidi2000** [comment]
Noted. Thank You.
